/**
 * Framework control catalog.
 *
 * The seeded library of controls per compliance framework, plus the curated
 * crosswalk between them. This file is the source of truth for the content;
 * the migration `prisma/migrations/*_framework_control_catalog` inserts the
 * same rows (generated by `npx tsx scripts/gen-framework-catalog-sql.ts`),
 * and `syncFrameworkCatalog()` upserts them for the demo seeder.
 *
 * Codes are the stable identity within a framework and must never change once
 * shipped — ComplianceMapping rows reference the catalog row by id, and the
 * migration's ON CONFLICT (framework, code) DO NOTHING relies on codes staying
 * put. Edit titles/descriptions freely; add new controls at the end of a
 * category with a fresh sortOrder.
 *
 * Content notes:
 * - NIST AI RMF 1.0 is represented at the category level (GOVERN 1..6,
 *   MAP 1..5, MEASURE 1..4, MANAGE 1..4). Subcategories are too granular for
 *   a per-system attestation and map many-to-one onto these anyway.
 * - ISO/IEC 42001:2023 uses the Annex A control identifiers.
 * - EU AI Act (Regulation (EU) 2024/1689) is represented by the articles that
 *   carry concrete provider/deployer obligations. Applicability depends on the
 *   system's risk tier; the classification wizard narrows the list.
 * - SOC 2 uses the 2017 Trust Services Criteria (CC1–CC9, A1, C1, PI1, P1–P8).
 */

import type { ComplianceFramework } from "@prisma/client";

export type CatalogFramework = Exclude<ComplianceFramework, "CUSTOM">;

export type CatalogControl = {
  framework: CatalogFramework;
  code: string;
  title: string;
  description: string;
  category: string;
  sortOrder: number;
};

export type CatalogCrosswalk = {
  from: { framework: CatalogFramework; code: string };
  to: { framework: CatalogFramework; code: string };
  note?: string;
};

export const FRAMEWORK_LABELS: Record<ComplianceFramework, string> = {
  EU_AI_ACT: "EU AI Act",
  NIST_AI_RMF: "NIST AI RMF",
  ISO_42001: "ISO/IEC 42001",
  SOC2: "SOC 2",
  COLORADO_AI: "Colorado AI law",
  NEW_YORK_AI: "New York AI laws",
  CUSTOM: "Custom",
};

export const FRAMEWORK_DESCRIPTIONS: Record<CatalogFramework, string> = {
  NIST_AI_RMF:
    "Voluntary US framework organised around four functions — Govern, Map, Measure, Manage — for managing risks to individuals, organisations and society from AI.",
  ISO_42001:
    "Certifiable AI management system standard. Annex A lists the controls an organisation implements to govern the responsible development and use of AI.",
  EU_AI_ACT:
    "Binding EU regulation with tiered obligations. Prohibited practices apply from February 2025, GPAI obligations from August 2025, and most high-risk requirements from August 2026.",
  SOC2:
    "AICPA Trust Services Criteria used for third-party assurance reports on security, availability, processing integrity, confidentiality and privacy.",
  COLORADO_AI:
    "Colorado SB 26-189 (signed May 2026; applies to decisions from January 1, 2027), which replaced SB 24-205 before it took effect. Notice, a plain-language explanation of adverse outcomes, data correction and human review for consequential decisions that automated decision-making technology materially influences; the earlier impact-assessment mandate was dropped. Attorney General enforcement only, with a 60-day cure period.",
  NEW_YORK_AI:
    "NYC Local Law 144 (bias-audited automated employment decision tools, enforced since July 2023), New York's algorithmic pricing disclosure law (GBL § 349-a), and the RAISE Act, which applies only to frontier-model developers (effective January 1, 2027).",
};

export const CATALOG_FRAMEWORKS: CatalogFramework[] = [
  "EU_AI_ACT",
  "NIST_AI_RMF",
  "ISO_42001",
  "SOC2",
  "COLORADO_AI",
  "NEW_YORK_AI",
];

export function isCatalogFramework(value: string): value is CatalogFramework {
  return (CATALOG_FRAMEWORKS as string[]).includes(value);
}

// ─── NIST AI RMF 1.0 ────────────────────────────────────────────────────────

const NIST: CatalogControl[] = [
  {
    code: "GOVERN 1",
    title: "Policies, processes and procedures for AI risk",
    description:
      "Policies, processes, procedures and practices across the organisation related to the mapping, measuring and managing of AI risks are in place, transparent and implemented effectively. Includes legal/regulatory tracking, risk tolerance, and lifecycle-wide risk management.",
    category: "Govern",
  },
  {
    code: "GOVERN 2",
    title: "Accountability structures",
    description:
      "Accountability structures are in place so that the appropriate teams and individuals are empowered, responsible and trained for mapping, measuring and managing AI risks. Roles and responsibilities are documented and executive leadership takes responsibility for AI risk decisions.",
    category: "Govern",
  },
  {
    code: "GOVERN 3",
    title: "Workforce diversity, equity, inclusion and accessibility",
    description:
      "Workforce diversity, equity, inclusion and accessibility processes are prioritised in the mapping, measuring and managing of AI risks throughout the lifecycle, and roles for human-AI configurations and oversight are defined.",
    category: "Govern",
  },
  {
    code: "GOVERN 4",
    title: "Culture of AI risk awareness",
    description:
      "Organisational teams are committed to a culture that considers and communicates AI risk. Practices foster critical thinking and safety-first mindsets, document risks and impacts, and test for risk before deployment.",
    category: "Govern",
  },
  {
    code: "GOVERN 5",
    title: "Engagement with relevant AI actors",
    description:
      "Processes are in place for robust engagement with relevant AI actors, including collecting and integrating feedback from external stakeholders and affected communities about system impacts.",
    category: "Govern",
  },
  {
    code: "GOVERN 6",
    title: "Third-party and supply chain risk policies",
    description:
      "Policies and procedures are in place to address AI risks and benefits arising from third-party software and data and other supply chain issues, including contingency processes for third-party failures.",
    category: "Govern",
  },
  {
    code: "MAP 1",
    title: "Context is established and understood",
    description:
      "Intended purposes, potentially beneficial uses, context-specific laws and norms, expectations and prospective settings for deployment are understood and documented, along with organisational risk tolerances and the business value of the system.",
    category: "Map",
  },
  {
    code: "MAP 2",
    title: "Categorisation of the AI system",
    description:
      "The AI system is categorised: the specific tasks and methods used to implement them (classifiers, generative models, recommenders), knowledge limits and the extent of human oversight are defined and documented.",
    category: "Map",
  },
  {
    code: "MAP 3",
    title: "Capabilities, usage, goals and expected benefits and costs",
    description:
      "AI capabilities, targeted usage, goals and expected benefits and costs compared with appropriate benchmarks are understood, including the potential for the system to be used in ways outside its intended purpose.",
    category: "Map",
  },
  {
    code: "MAP 4",
    title: "Risks and benefits of all components",
    description:
      "Risks and benefits are mapped for all components of the AI system including third-party software, pre-trained models and data. Internal risk controls for third-party components are identified and documented.",
    category: "Map",
  },
  {
    code: "MAP 5",
    title: "Impacts to individuals, groups, communities and society",
    description:
      "Likelihood and magnitude of each identified impact — positive or negative — to individuals, groups, communities, organisations and society are characterised, informed by engagement with affected parties.",
    category: "Map",
  },
  {
    code: "MEASURE 1",
    title: "Appropriate methods and metrics",
    description:
      "Approaches and metrics for measurement of AI risks enumerated during the MAP function are selected, applied and documented, including metrics for risks that cannot be measured directly. Independent assessors are involved where appropriate.",
    category: "Measure",
  },
  {
    code: "MEASURE 2",
    title: "Evaluation for trustworthy characteristics",
    description:
      "AI systems are evaluated for trustworthy characteristics: validity and reliability, safety, security and resilience, accountability and transparency, explainability, privacy, and fairness with harmful bias managed. Evaluations use representative conditions and test sets.",
    category: "Measure",
  },
  {
    code: "MEASURE 3",
    title: "Tracking identified risks over time",
    description:
      "Mechanisms for tracking identified AI risks over time are in place, including approaches for identifying and tracking emergent risks and end-user/affected-party feedback about performance.",
    category: "Measure",
  },
  {
    code: "MEASURE 4",
    title: "Feedback about measurement efficacy",
    description:
      "Feedback about the efficacy of measurement is gathered and assessed. Measurement approaches are connected to deployment context and are validated with domain experts and affected users.",
    category: "Measure",
  },
  {
    code: "MANAGE 1",
    title: "Risks are prioritised, responded to and managed",
    description:
      "AI risks based on assessments and other analytical output from the MAP and MEASURE functions are prioritised, responded to and managed. Go/no-go decisions are documented; residual risks are documented for downstream acquirers and end users.",
    category: "Manage",
  },
  {
    code: "MANAGE 2",
    title: "Strategies to maximise benefits and minimise negative impacts",
    description:
      "Strategies to maximise AI benefits and minimise negative impacts are planned, prepared, implemented, documented and informed by input from relevant AI actors, including mechanisms to supersede, disengage or deactivate systems that perform inconsistently with intended use.",
    category: "Manage",
  },
  {
    code: "MANAGE 3",
    title: "Third-party risks and benefits are managed",
    description:
      "AI risks and benefits from third-party entities — pre-trained models, vendor-hosted services, external data — are regularly monitored, and risk controls are applied and documented.",
    category: "Manage",
  },
  {
    code: "MANAGE 4",
    title: "Risk treatments, response, recovery and communication plans",
    description:
      "Risk treatments including response and recovery, and communication plans for the identified and measured AI risks, are documented and monitored regularly. Post-deployment monitoring, incident response and change management are in place.",
    category: "Manage",
  },
].map((c, i) => ({ ...c, framework: "NIST_AI_RMF" as const, sortOrder: (i + 1) * 10 }));

// ─── ISO/IEC 42001:2023 Annex A ─────────────────────────────────────────────

const ISO: CatalogControl[] = [
  { code: "A.2.2", category: "A.2 Policies related to AI", title: "AI policy", description: "The organisation documents a policy for the development or use of AI systems, aligned with business strategy, values, and legal requirements, and communicates it to relevant parties." },
  { code: "A.2.3", category: "A.2 Policies related to AI", title: "Alignment with other organisational policies", description: "The organisation determines where other policies (security, privacy, quality, risk) are affected by or apply to its objectives with respect to AI systems, and reconciles them." },
  { code: "A.2.4", category: "A.2 Policies related to AI", title: "Review of the AI policy", description: "The AI policy is reviewed at planned intervals or when significant changes occur to ensure continuing suitability, adequacy and effectiveness." },
  { code: "A.3.2", category: "A.3 Internal organisation", title: "AI roles and responsibilities", description: "Roles and responsibilities for AI are defined and allocated according to the needs of the organisation, covering risk management, impact assessment, development, operations and oversight." },
  { code: "A.3.3", category: "A.3 Internal organisation", title: "Reporting of concerns", description: "A process is defined for reporting concerns about the organisation's role with respect to an AI system throughout its lifecycle, with protection for those raising concerns." },
  { code: "A.4.2", category: "A.4 Resources for AI systems", title: "Resource documentation", description: "Relevant resources required for the activities at given AI system lifecycle stages are identified and documented: data, tooling, system and computing, and human resources." },
  { code: "A.4.3", category: "A.4 Resources for AI systems", title: "Data resources", description: "Information about the data resources used for the AI system is documented, including provenance, categories, intended use, and known quality and bias characteristics." },
  { code: "A.4.4", category: "A.4 Resources for AI systems", title: "Tooling resources", description: "Information about the tooling resources used for the AI system — development frameworks, evaluation tools, deployment platforms — is documented." },
  { code: "A.4.5", category: "A.4 Resources for AI systems", title: "System and computing resources", description: "Information about the system and computing resources used for the AI system is documented, including hosting location, capacity and dependencies." },
  { code: "A.4.6", category: "A.4 Resources for AI systems", title: "Human resources", description: "Information about the human resources and their competences used for the development, deployment, operation, change management, maintenance and oversight of the AI system is documented." },
  { code: "A.5.2", category: "A.5 Assessing impacts of AI systems", title: "AI system impact assessment process", description: "A process is established to assess the potential consequences for individuals, groups and societies that can result from the AI system throughout its lifecycle." },
  { code: "A.5.3", category: "A.5 Assessing impacts of AI systems", title: "Documentation of AI system impact assessments", description: "Results of AI system impact assessments are documented and retained for a defined period." },
  { code: "A.5.4", category: "A.5 Assessing impacts of AI systems", title: "Impact on individuals or groups of individuals", description: "Potential impacts of the AI system on individuals or groups — fairness, safety, privacy, accessibility, human rights — are assessed and documented." },
  { code: "A.5.5", category: "A.5 Assessing impacts of AI systems", title: "Societal impacts of AI systems", description: "Potential societal impacts of the AI system — environmental, economic, governmental, cultural — are assessed and documented." },
  { code: "A.6.1.2", category: "A.6 AI system life cycle", title: "Objectives for responsible development", description: "Objectives guiding the responsible development of AI systems are identified, documented, and integrated into development measures." },
  { code: "A.6.1.3", category: "A.6 AI system life cycle", title: "Processes for responsible design and development", description: "Specific processes for the responsible design and development of the AI system are defined and documented, covering the full lifecycle from requirements to retirement." },
  { code: "A.6.2.2", category: "A.6 AI system life cycle", title: "AI system requirements and specification", description: "Requirements for new AI systems or material enhancements are specified and documented, including intended purpose, performance criteria and constraints." },
  { code: "A.6.2.3", category: "A.6 AI system life cycle", title: "Documentation of AI system design and development", description: "The design and development of the AI system is documented based on organisational objectives, documented requirements and specification criteria." },
  { code: "A.6.2.4", category: "A.6 AI system life cycle", title: "AI system verification and validation", description: "Verification and validation measures for the AI system are defined and documented, and the criteria for their use are specified, including test data, metrics and acceptance thresholds." },
  { code: "A.6.2.5", category: "A.6 AI system life cycle", title: "AI system deployment", description: "A deployment plan is documented and the necessary requirements are met before deployment, including approval gates and rollback provisions." },
  { code: "A.6.2.6", category: "A.6 AI system life cycle", title: "AI system operation and monitoring", description: "Necessary elements for the ongoing operation of the AI system are defined and documented, including performance monitoring, drift detection and error handling." },
  { code: "A.6.2.7", category: "A.6 AI system life cycle", title: "AI system technical documentation", description: "Technical documentation for each relevant lifecycle stage is prepared and provided to interested parties as required, including model architecture, data, evaluation and known limitations." },
  { code: "A.6.2.8", category: "A.6 AI system life cycle", title: "AI system recording of event logs", description: "Event logs are recorded automatically during operation for a defined period, to support traceability, incident investigation and audit." },
  { code: "A.7.2", category: "A.7 Data for AI systems", title: "Data for development and enhancement", description: "Data management processes related to the development of AI systems are defined, documented and implemented, covering privacy, security, transparency and traceability of data." },
  { code: "A.7.3", category: "A.7 Data for AI systems", title: "Acquisition of data", description: "Details about the acquisition and selection of data used in AI systems are determined and documented, including sources, rights and consent." },
  { code: "A.7.4", category: "A.7 Data for AI systems", title: "Quality of data for AI systems", description: "Requirements for data quality are defined and data used to develop and operate the AI system is ensured to meet them, including representativeness and bias checks." },
  { code: "A.7.5", category: "A.7 Data for AI systems", title: "Data provenance", description: "A process to record the provenance of data used in AI systems over their lifecycle is defined and documented." },
  { code: "A.7.6", category: "A.7 Data for AI systems", title: "Data preparation", description: "Criteria for selecting data preparation methods and the methods used (cleaning, labelling, augmentation, splitting) are defined and documented." },
  { code: "A.8.2", category: "A.8 Information for interested parties", title: "System documentation and information for users", description: "Necessary information about the AI system is determined and provided to users, including capabilities, limitations, intended use and human oversight measures." },
  { code: "A.8.3", category: "A.8 Information for interested parties", title: "External reporting", description: "Interested parties are provided with the capability to report adverse impacts of the AI system." },
  { code: "A.8.4", category: "A.8 Information for interested parties", title: "Communication of incidents", description: "A plan for communicating incidents to users and other interested parties is defined and documented." },
  { code: "A.8.5", category: "A.8 Information for interested parties", title: "Information for interested parties", description: "The organisation determines and documents its obligations to report information about the AI system to interested parties, including regulators." },
  { code: "A.9.2", category: "A.9 Use of AI systems", title: "Processes for responsible use of AI systems", description: "Processes for the responsible use of AI systems are defined and documented, covering acceptable use, monitoring and escalation." },
  { code: "A.9.3", category: "A.9 Use of AI systems", title: "Objectives for responsible use", description: "Objectives guiding the responsible use of AI systems are identified, documented and applied." },
  { code: "A.9.4", category: "A.9 Use of AI systems", title: "Intended use of the AI system", description: "The AI system is used according to its intended uses and accompanying documentation; deviations are identified and managed." },
  { code: "A.10.2", category: "A.10 Third-party and customer relationships", title: "Allocating responsibilities", description: "Responsibilities within the AI system lifecycle are allocated between the organisation, its partners, suppliers, customers and third parties, and documented." },
  { code: "A.10.3", category: "A.10 Third-party and customer relationships", title: "Suppliers", description: "A process is established to ensure that the organisation's use of services, products or materials provided by suppliers aligns with its approach to responsible AI." },
  { code: "A.10.4", category: "A.10 Third-party and customer relationships", title: "Customers", description: "The organisation ensures its responsible approach to AI considers customer expectations and needs, and provides the information customers require." },
].map((c, i) => ({ ...c, framework: "ISO_42001" as const, sortOrder: (i + 1) * 10 }));

// ─── EU AI Act (Regulation (EU) 2024/1689) ──────────────────────────────────

const EU: CatalogControl[] = [
  { code: "Art. 4", category: "Chapter I — General provisions", title: "AI literacy", description: "Providers and deployers take measures to ensure a sufficient level of AI literacy of their staff and other persons dealing with the operation and use of AI systems on their behalf, taking into account their technical knowledge, context of use and the persons affected." },
  { code: "Art. 5", category: "Chapter II — Prohibited practices", title: "Prohibited AI practices", description: "The system does not engage in a prohibited practice: subliminal or manipulative techniques causing significant harm, exploitation of vulnerabilities, social scoring, predictive policing based solely on profiling, untargeted facial-image scraping, emotion recognition in workplaces or education, biometric categorisation inferring protected attributes, or real-time remote biometric identification in public spaces for law enforcement (save narrow exceptions)." },
  { code: "Art. 9", category: "Chapter III — High-risk: requirements", title: "Risk management system", description: "A continuous, iterative risk management system is established, implemented, documented and maintained throughout the lifecycle of the high-risk AI system: identify and analyse known and reasonably foreseeable risks, evaluate risks from intended use and misuse, adopt targeted risk management measures, and test against defined metrics." },
  { code: "Art. 10", category: "Chapter III — High-risk: requirements", title: "Data and data governance", description: "Training, validation and testing data sets are subject to data governance and management practices appropriate for the intended purpose: design choices, provenance and collection, preparation, assumptions, bias examination and mitigation, gaps and shortcomings, and relevance/representativeness for the deployment context." },
  { code: "Art. 11", category: "Chapter III — High-risk: requirements", title: "Technical documentation", description: "Technical documentation is drawn up before the system is placed on the market or put into service and kept up to date, demonstrating compliance with Section 2 requirements and containing at minimum the elements in Annex IV." },
  { code: "Art. 12", category: "Chapter III — High-risk: requirements", title: "Record-keeping", description: "The system technically allows for the automatic recording of events (logs) over its lifetime, at a level of traceability appropriate to the intended purpose, enabling identification of risk situations, post-market monitoring and deployer oversight." },
  { code: "Art. 13", category: "Chapter III — High-risk: requirements", title: "Transparency and provision of information to deployers", description: "The system is designed so its operation is sufficiently transparent for deployers to interpret and use the output appropriately, and is accompanied by instructions for use covering characteristics, capabilities, limitations, performance, human oversight measures and expected lifetime." },
  { code: "Art. 14", category: "Chapter III — High-risk: requirements", title: "Human oversight", description: "The system is designed and developed so it can be effectively overseen by natural persons during use, with measures enabling overseers to understand capacities and limitations, remain aware of automation bias, correctly interpret output, decide not to use or to override the system, and intervene or halt it." },
  { code: "Art. 15", category: "Chapter III — High-risk: requirements", title: "Accuracy, robustness and cybersecurity", description: "The system achieves an appropriate level of accuracy, robustness and cybersecurity and performs consistently throughout its lifecycle, with declared accuracy metrics, resilience to errors and faults, and protection against data poisoning, model poisoning, adversarial examples and confidentiality attacks." },
  { code: "Art. 16", category: "Chapter III — High-risk: provider obligations", title: "Obligations of providers of high-risk AI systems", description: "Providers ensure compliance with Section 2 requirements, indicate their name and contact details, have a quality management system, keep documentation and logs, undergo conformity assessment, draw up an EU declaration of conformity, affix CE marking, register the system, take corrective actions and cooperate with authorities." },
  { code: "Art. 17", category: "Chapter III — High-risk: provider obligations", title: "Quality management system", description: "A quality management system is in place, documented as written policies, procedures and instructions, covering regulatory compliance strategy, design and development control, testing and validation, technical specifications, data management, risk management, post-market monitoring, incident reporting, communication with authorities, record-keeping, resource management and accountability." },
  { code: "Art. 26", category: "Chapter III — High-risk: deployer obligations", title: "Obligations of deployers of high-risk AI systems", description: "Deployers use the system in accordance with its instructions, assign human oversight to competent and trained persons, ensure input data is relevant and representative, monitor operation and inform the provider/distributor of risks or incidents, keep logs for at least six months, inform workers' representatives and affected persons where applicable, and cooperate with authorities." },
  { code: "Art. 27", category: "Chapter III — High-risk: deployer obligations", title: "Fundamental rights impact assessment", description: "Before deploying a high-risk AI system, deployers that are public bodies or private entities providing public services (and deployers of credit-scoring or life/health insurance risk systems) perform an assessment of the impact on fundamental rights: processes, period and frequency of use, categories of persons affected, specific risks of harm, human oversight measures, and measures if risks materialise." },
  { code: "Art. 43", category: "Chapter III — High-risk: conformity", title: "Conformity assessment", description: "The applicable conformity assessment procedure is followed before the system is placed on the market or put into service — internal control (Annex VI) or a notified-body assessment of the quality management system and technical documentation (Annex VII) — and repeated after substantial modification." },
  { code: "Art. 49", category: "Chapter III — High-risk: conformity", title: "Registration in the EU database", description: "The provider (and, for public-authority deployers, the deployer) registers the high-risk AI system in the EU database referred to in Article 71 before placing it on the market or putting it into service." },
  { code: "Art. 50", category: "Chapter IV — Transparency obligations", title: "Transparency obligations for certain AI systems", description: "Systems intended to interact directly with natural persons inform them they are interacting with AI; synthetic audio, image, video or text output is marked in a machine-readable format; deployers of emotion recognition or biometric categorisation inform exposed persons; deep fakes and AI-generated text on matters of public interest are disclosed." },
  { code: "Art. 53", category: "Chapter V — General-purpose AI models", title: "Obligations for providers of general-purpose AI models", description: "Providers of GPAI models draw up and maintain technical documentation, provide information to downstream providers, put in place a copyright-compliance policy, and publish a sufficiently detailed summary of training content. Deployers should confirm their GPAI provider meets these obligations." },
  { code: "Art. 72", category: "Chapter IX — Post-market monitoring", title: "Post-market monitoring by providers", description: "A post-market monitoring system is established and documented, proportionate to the nature of the AI technologies and risks, that actively and systematically collects, documents and analyses performance data throughout the system's lifetime to evaluate continuous compliance." },
  { code: "Art. 73", category: "Chapter IX — Post-market monitoring", title: "Reporting of serious incidents", description: "Serious incidents are reported to the market surveillance authorities of the Member State where the incident occurred, immediately after a causal link is established and no later than 15 days (2 days for widespread infringement, 10 days for death), followed by investigation and corrective action." },
].map((c, i) => ({ ...c, framework: "EU_AI_ACT" as const, sortOrder: (i + 1) * 10 }));

// ─── SOC 2 Trust Services Criteria (2017) ───────────────────────────────────

const SOC2: CatalogControl[] = [
  { code: "CC1", category: "Common criteria", title: "Control environment", description: "The entity demonstrates a commitment to integrity and ethical values, board oversight, defined structures and reporting lines, commitment to competence, and accountability for internal control — including for AI-enabled processes." },
  { code: "CC2", category: "Common criteria", title: "Communication and information", description: "The entity obtains or generates relevant, quality information to support internal control and communicates internally and externally the objectives and responsibilities for internal control, including how AI systems are used." },
  { code: "CC3", category: "Common criteria", title: "Risk assessment", description: "The entity specifies objectives clearly enough to identify and assess risks, identifies and analyses risks to achieving them, considers the potential for fraud, and identifies changes (including new AI capabilities) that could significantly affect internal control." },
  { code: "CC4", category: "Common criteria", title: "Monitoring activities", description: "The entity selects, develops and performs ongoing and separate evaluations to ascertain whether controls are present and functioning, and evaluates and communicates deficiencies in a timely manner." },
  { code: "CC5", category: "Common criteria", title: "Control activities", description: "The entity selects and develops control activities that contribute to mitigating risks, including general controls over technology, and deploys them through policies and procedures." },
  { code: "CC6", category: "Common criteria", title: "Logical and physical access controls", description: "Logical access security software, infrastructure and architectures are implemented over protected information assets; access is provisioned, restricted and removed appropriately; credentials, encryption and physical access are managed." },
  { code: "CC7", category: "Common criteria", title: "System operations", description: "The entity detects and monitors configuration changes and vulnerabilities, monitors system components for anomalies, evaluates security events, responds to incidents, and recovers from them." },
  { code: "CC8", category: "Common criteria", title: "Change management", description: "The entity authorises, designs, develops, configures, documents, tests, approves and implements changes to infrastructure, data, software and procedures — including model and prompt changes — to meet its objectives." },
  { code: "CC9", category: "Common criteria", title: "Risk mitigation", description: "The entity identifies, selects and develops risk mitigation activities for risks arising from potential business disruptions, and assesses and manages risks associated with vendors and business partners." },
  { code: "A1", category: "Availability", title: "Availability", description: "The entity maintains, monitors and evaluates current processing capacity, authorises and implements environmental protections and backup/recovery infrastructure, and tests recovery plan procedures." },
  { code: "C1", category: "Confidentiality", title: "Confidentiality", description: "The entity identifies and maintains confidential information to meet its objectives and disposes of it when no longer needed — including prompts, outputs and training data containing confidential information." },
  { code: "PI1", category: "Processing integrity", title: "Processing integrity", description: "The entity obtains or generates, uses and communicates relevant quality information regarding processing objectives; implements policies over system inputs, processing and outputs so they are complete, accurate, timely and authorised; and stores inputs and outputs completely and accurately." },
  { code: "P1", category: "Privacy", title: "Notice and communication of objectives", description: "The entity provides notice to data subjects about its privacy practices and objectives, including how personal information is used in AI processing." },
  { code: "P2", category: "Privacy", title: "Choice and consent", description: "The entity communicates choices available regarding the collection, use, retention, disclosure and disposal of personal information and obtains consent where required." },
  { code: "P3", category: "Privacy", title: "Collection", description: "The entity collects personal information consistent with its objectives related to privacy, and obtains explicit consent for sensitive information." },
  { code: "P4", category: "Privacy", title: "Use, retention and disposal", description: "The entity limits use of personal information to the purposes identified, retains it only as long as necessary, and securely disposes of it." },
  { code: "P5", category: "Privacy", title: "Access", description: "The entity grants data subjects access to their personal information for review and correction." },
  { code: "P6", category: "Privacy", title: "Disclosure and notification", description: "The entity discloses personal information to third parties only with consent or as permitted, assesses third-party compliance, and notifies affected parties of breaches and incidents." },
  { code: "P7", category: "Privacy", title: "Quality", description: "The entity collects and maintains accurate, up-to-date, complete and relevant personal information." },
  { code: "P8", category: "Privacy", title: "Monitoring and enforcement", description: "The entity implements a process for receiving, addressing, resolving and communicating the resolution of inquiries, complaints and disputes, and monitors compliance with its privacy commitments." },
].map((c, i) => ({ ...c, framework: "SOC2" as const, sortOrder: (i + 1) * 10 }));

// ─── Colorado SB 26-189 (automated decision-making technology) ─────────────
//
// Enrolled act, C.R.S. 6-1-1701 to 6-1-1709 (part 17 of article 1, title 6),
// repealing and reenacting SB 24-205 before it took effect. Signed 2026-05-14;
// applies to consequential decisions made on or after 2027-01-01. The
// Attorney General must adopt post-adverse-outcome disclosure and
// consumer-rights rules on or before 2027-01-01, so wording below may need
// to follow those rules. Codes are descriptive ("CO-n"), not statute
// sections, because one section often yields several attestable controls.

const COLORADO: CatalogControl[] = [
  { code: "CO-1", category: "Scoping", title: "Covered ADMT and consequential-decision inventory", description: "Identify each automated decision-making technology (ADMT) that materially influences — is a non-de minimis factor that affects the outcome of — a decision about access to, eligibility for, selection for or pricing in a covered domain: education enrollment or opportunity, employment, lease or purchase of Colorado residential real estate, financial or lending services, insurance, health-care services, or essential government services and public benefits. Record exclusions relied on (routine or low-stakes uses, summarising for human review) and sector carve-outs (insurers under 10-3-1104.9, HIPAA covered entities other than for employment, FDA-overseen devices, GLBA data). Applies to decisions made on or after January 1, 2027." },
  { code: "CO-2", category: "Deployer", title: "Notice before the decision", description: "Before using a covered ADMT to materially influence a consequential decision, give the consumer clear and conspicuous notice that one is or will be used, with instructions for getting the additional information the Act requires. A prominent public notice reasonably accessible at points of consumer interaction, such as a link or posting near the interaction, satisfies this (6-1-1704(1)–(2))." },
  { code: "CO-3", category: "Deployer", title: "Disclosure within 30 days of an adverse outcome", description: "Within 30 days of a decision with an adverse outcome, give the consumer a plain-language description of the decision and the ADMT's role in it; a simple process to request the ADMT's name, version, developer and the types, categories and sources of personal data used (to the extent the developer supplied them); and an explanation of the consumer's rights and how to exercise them. If trade secrets or legally protected information are withheld, tell the consumer. Creditors may rely on ECOA/FCRA notices that also satisfy these elements (6-1-1704(3), (5), (6))." },
  { code: "CO-4", category: "Deployer", title: "Data access and correction on request", description: "After an adverse outcome, give the consumer, on request, instructions for requesting their personal data and for correcting factually incorrect or materially inaccurate personal data used in the decision. Correction does not extend to opinions, predictions, scores or protected evaluations (6-1-1705(1)(a)(I), (1)(c))." },
  { code: "CO-5", category: "Deployer", title: "Meaningful human review and reconsideration", description: "After an adverse outcome, on request, offer meaningful human review and reconsideration of the decision to the extent commercially reasonable. The reviewer must be designated by the deployer, have authority to approve, modify or override the decision, consider relevant primary evidence, be trained, not default to the system output, and understand the output's intended use, limitations, input categories and principal factors (6-1-1701(15), 6-1-1705(1)(a)(II))." },
  { code: "CO-6", category: "Deployer", title: "Accessible notices and disclosures", description: "Provide every notice and disclosure under the Act in a manner reasonably accessible to consumers with disabilities and consumers with limited English proficiency, consistent with applicable law. Education deployers subject to FERPA may use their FERPA channels (6-1-1704(8)–(9))." },
  { code: "CO-7", category: "Developer", title: "Developer documentation to deployers", description: "From January 1, 2027, developers of a covered ADMT marketed or configured for consequential decisions make available to each deployer: intended uses and known harmful or inappropriate uses; categories of training data, to the extent known; known limitations, risks and circumstances in which it should not be used; instructions for appropriate use, monitoring and meaningful human review; and information reasonably necessary for the deployer to give the CO-3 disclosures, noting if any is withheld. Deployers obtain and keep this for each in-scope system (6-1-1702(1), (3))." },
  { code: "CO-8", category: "Developer", title: "Notice of material updates", description: "Developers give each deployer notice, within a reasonable time, of material updates, intentional and substantial modifications, and changes to intended use, limitations or risk mitigation. Public release notes suffice if the developer also directly notifies each deployer of the release. Deployers have a process to receive, review and re-assess the system after such a notice (6-1-1702(2))." },
  { code: "CO-9", category: "Records", title: "Records retained for three years", description: "Developers keep records reasonably necessary to show compliance — system version identifiers, changelogs, and documentation and notices of material updates — for at least three years after the record is created. Deployers keep such records, which may include ADMT version identifiers, changelogs and documentation of material mitigation changes, for at least three years after the date of the consequential decision. Longer where other law requires (6-1-1702(4), 6-1-1703)." },
  { code: "CO-10", category: "Liability", title: "Fault allocation and contract terms", description: "Developers and deployers can each be liable under Colorado anti-discrimination law for a decision a covered ADMT materially influenced, with fault allocated by relative fault. A contract term that indemnifies a party for its own discriminatory acts in using an ADMT is void. Using an ADMT, or complying with the Act, is not a defense to other legal obligations. Review vendor and customer contracts and documented intended-use limits accordingly (6-1-1707, 6-1-1709)." },
  { code: "CO-11", category: "Enforcement", title: "Attorney General enforcement and cure readiness", description: "A violation is a deceptive trade practice enforced exclusively by the Attorney General; there is no private right of action. Before any enforcement action the Attorney General issues a notice of violation where cure is possible, and the entity has 60 days to cure; no cure period is required for knowing or repeated violations. The cure provision is repealed January 1, 2030. Keep a named owner, evidence for each control above, and a remediation path ready (6-1-1706)." },
].map((c, i) => ({ ...c, framework: "COLORADO_AI" as const, sortOrder: (i + 1) * 10 }));

// ─── New York ──────────────────────────────────────────────────────────────
//
// NYC Local Law 144 of 2021 (Admin. Code § 20-870 to 20-874, effective
// 2023-01-01; enforcement began 2023-07-05) and the DCWP rules at 6 RCNY
// §§ 5-300 to 5-304; the State algorithmic pricing disclosure in General
// Business Law § 349-a; and the RAISE Act (GBL article 44-B, chapter 96 of
// 2026, effective 2027-01-01), which reaches only frontier-model developers.
// The RAISE text reviewed is A.9449 as introduced; the enacted version was
// carried as S.8828 and was not compared line by line.

const NEW_YORK: CatalogControl[] = [
  { code: "NY-1", category: "NYC Local Law 144", title: "AEDT inventory", description: "Identify each automated employment decision tool (AEDT) used to screen candidates for employment or employees for promotion within New York City. A tool is in scope when its simplified output (score, tag, classification, ranking) is the sole basis for the decision, is weighted more than any other criterion, or is used to overrule other conclusions including human judgment (6 RCNY § 5-300). Junk-mail filters, firewalls, calculators and spreadsheets are out. Penalties: up to $500 for a first violation, $500–$1,500 for each later one; each day of use and each missing notice is a separate violation (§ 20-872)." },
  { code: "NY-2", category: "NYC Local Law 144", title: "Independent bias audit within one year", description: "Do not use or continue to use an AEDT if more than one year has passed since its last bias audit. The auditor must be independent: not involved in using, developing or distributing the tool, and with no employment or financial relationship with the employer or vendor. For tools that select or classify, calculate selection rate and impact ratio by sex, by race/ethnicity and by their intersections (EEO-1 component 1 categories), report individuals in unknown categories, and, for scoring tools, scoring rate. Categories under 2% of the data may be excluded with justification (§ 20-871(a)(1); 6 RCNY § 5-301)." },
  { code: "NY-3", category: "NYC Local Law 144", title: "Publish the audit summary", description: "Before using the AEDT, publish clearly and conspicuously on the employment section of the website: the date of the latest bias audit; a summary of results, including the data source and explanation, unknown-category count, applicant counts, selection or scoring rates and impact ratios for all categories; and the date the employer began using the tool. A clearly labelled hyperlink is enough. Keep it posted for at least 6 months after the tool's latest use (§ 20-871(a)(2); 6 RCNY § 5-303)." },
  { code: "NY-4", category: "NYC Local Law 144", title: "Notice at least 10 business days before use", description: "At least 10 business days before use, tell each candidate or employee who resides in New York City that an AEDT will be used and the job qualifications and characteristics it will use. Candidates may be notified on the employment section of the website, in the job posting, or by mail or email; employees may also be notified through a written policy (§ 20-871(b)(1)–(2); 6 RCNY § 5-304(b)–(c))." },
  { code: "NY-5", category: "NYC Local Law 144", title: "Alternative-process instructions and data-practice disclosure", description: "The notice must include instructions for requesting an alternative selection process or a reasonable accommodation, where available; the rules do not require an employer to provide an alternative process. Also publish the type of data the AEDT collects, its source and the retention policy, with instructions for a written request; answer written requests within 30 days, explaining any refusal that law or a law-enforcement investigation requires (§ 20-871(b)(1), (3); 6 RCNY § 5-304(a), (d))." },
  { code: "NY-6", category: "Algorithmic pricing", title: "Personalized algorithmic pricing disclosure", description: "When an entity sets a New York consumer's price with an algorithm using that consumer's personal data and advertises or displays it to them, include with the price the clear and conspicuous statement \"THIS PRICE WAS SET BY AN ALGORITHM USING YOUR PERSONAL DATA\", in the same medium and at or near the price. Insurers, GLBA financial institutions and lower prices for existing subscribers are excluded. The Attorney General may seek penalties up to $1,000 per violation after a cure period (GBL § 349-a)." },
  { code: "NY-7", category: "RAISE Act", title: "Frontier AI framework and transparency report", description: "Applies only to developers of frontier models (trained with more than 10^26 operations). Large frontier developers (with affiliates, over $500M annual gross revenue) publish a frontier AI framework covering how they assess and mitigate catastrophic risk, review and update it at least annually, and publish material changes within 30 days. Every frontier developer publishes a transparency report on or before deploying a new or substantially modified frontier model; large developers add summaries of their catastrophic-risk assessments. No materially false statements about catastrophic risk. Effective January 1, 2027 (GBL § 1421)." },
  { code: "NY-8", category: "RAISE Act", title: "Critical safety incident reporting", description: "Frontier developers report a critical safety incident to the state office within 72 hours of determining it occurred or learning facts sufficient for a reasonable belief it did, and within 24 hours to an appropriate authority if it poses imminent risk of death or serious injury. Large frontier developers send the office a summary of internal-use catastrophic-risk assessments every three months. Penalties up to $1M for a first violation and $3M thereafter, by the Attorney General (GBL §§ 1422, 1427)." },
  { code: "NY-9", category: "RAISE Act", title: "Large frontier developer disclosure statement", description: "A large frontier developer may not develop, deploy or operate a frontier model in New York without a current disclosure statement filed with the Department of Financial Services office and the pro-rata assessment paid. The statement names the developer, its New York offices, qualifying owners and three contacts, and is renewed every two years or on a transfer or material change. $1,000 per day for failure to file (GBL § 1428)." },
].map((c, i) => ({ ...c, framework: "NEW_YORK_AI" as const, sortOrder: (i + 1) * 10 }));

export const FRAMEWORK_CATALOG: CatalogControl[] = [...EU, ...NIST, ...ISO, ...SOC2, ...COLORADO, ...NEW_YORK];

// ─── Crosswalk ──────────────────────────────────────────────────────────────
//
// Each entry links two controls that address the same underlying obligation
// closely enough that evidence for one is meaningful evidence for the other.
// Written compactly as `from -> [to, to, ...]`; pairs are undirected.

type XwSpec = [CatalogFramework, string, Array<[CatalogFramework, string]>];

const XW: XwSpec[] = [
  // NIST Govern
  ["NIST_AI_RMF", "GOVERN 1", [["ISO_42001", "A.2.2"], ["ISO_42001", "A.2.3"], ["ISO_42001", "A.2.4"], ["EU_AI_ACT", "Art. 17"], ["SOC2", "CC1"], ["SOC2", "CC5"]]],
  ["NIST_AI_RMF", "GOVERN 2", [["ISO_42001", "A.3.2"], ["ISO_42001", "A.4.6"], ["EU_AI_ACT", "Art. 4"], ["EU_AI_ACT", "Art. 16"], ["SOC2", "CC1"]]],
  ["NIST_AI_RMF", "GOVERN 3", [["ISO_42001", "A.5.4"]]],
  ["NIST_AI_RMF", "GOVERN 4", [["ISO_42001", "A.3.3"], ["SOC2", "CC2"]]],
  ["NIST_AI_RMF", "GOVERN 5", [["ISO_42001", "A.8.3"], ["ISO_42001", "A.8.5"], ["SOC2", "CC2"]]],
  ["NIST_AI_RMF", "GOVERN 6", [["ISO_42001", "A.10.2"], ["ISO_42001", "A.10.3"], ["SOC2", "CC9"]]],
  // NIST Map
  ["NIST_AI_RMF", "MAP 1", [["ISO_42001", "A.6.2.2"], ["ISO_42001", "A.9.4"], ["EU_AI_ACT", "Art. 5"], ["EU_AI_ACT", "Art. 9"]]],
  ["NIST_AI_RMF", "MAP 2", [["ISO_42001", "A.6.2.2"], ["EU_AI_ACT", "Art. 9"]]],
  ["NIST_AI_RMF", "MAP 3", [["ISO_42001", "A.6.1.2"], ["ISO_42001", "A.9.3"]]],
  ["NIST_AI_RMF", "MAP 4", [["ISO_42001", "A.4.3"], ["ISO_42001", "A.7.3"], ["ISO_42001", "A.10.3"], ["EU_AI_ACT", "Art. 10"]]],
  ["NIST_AI_RMF", "MAP 5", [["ISO_42001", "A.5.2"], ["ISO_42001", "A.5.3"], ["ISO_42001", "A.5.4"], ["ISO_42001", "A.5.5"], ["EU_AI_ACT", "Art. 27"]]],
  // NIST Measure
  ["NIST_AI_RMF", "MEASURE 1", [["ISO_42001", "A.6.2.4"], ["EU_AI_ACT", "Art. 15"]]],
  ["NIST_AI_RMF", "MEASURE 2", [["ISO_42001", "A.6.2.4"], ["ISO_42001", "A.7.4"], ["EU_AI_ACT", "Art. 10"], ["EU_AI_ACT", "Art. 15"]]],
  ["NIST_AI_RMF", "MEASURE 3", [["ISO_42001", "A.6.2.6"], ["ISO_42001", "A.6.2.8"], ["EU_AI_ACT", "Art. 12"], ["EU_AI_ACT", "Art. 72"]]],
  ["NIST_AI_RMF", "MEASURE 4", [["ISO_42001", "A.6.2.6"], ["EU_AI_ACT", "Art. 72"]]],
  // NIST Manage
  ["NIST_AI_RMF", "MANAGE 1", [["ISO_42001", "A.6.2.5"], ["EU_AI_ACT", "Art. 9"], ["SOC2", "CC3"]]],
  ["NIST_AI_RMF", "MANAGE 2", [["ISO_42001", "A.6.1.3"], ["ISO_42001", "A.9.2"], ["EU_AI_ACT", "Art. 14"]]],
  ["NIST_AI_RMF", "MANAGE 3", [["ISO_42001", "A.10.3"], ["ISO_42001", "A.10.4"], ["EU_AI_ACT", "Art. 26"], ["SOC2", "CC9"]]],
  ["NIST_AI_RMF", "MANAGE 4", [["ISO_42001", "A.8.4"], ["EU_AI_ACT", "Art. 73"], ["SOC2", "CC7"]]],
  // ISO -> EU / SOC2 (pairs not already covered above)
  ["ISO_42001", "A.3.3", [["SOC2", "CC2"]]],
  ["ISO_42001", "A.4.3", [["SOC2", "C1"], ["SOC2", "P4"]]],
  ["ISO_42001", "A.4.6", [["EU_AI_ACT", "Art. 4"]]],
  ["ISO_42001", "A.5.2", [["EU_AI_ACT", "Art. 27"]]],
  ["ISO_42001", "A.6.2.3", [["EU_AI_ACT", "Art. 11"]]],
  ["ISO_42001", "A.6.2.4", [["EU_AI_ACT", "Art. 15"], ["EU_AI_ACT", "Art. 43"]]],
  ["ISO_42001", "A.6.2.5", [["SOC2", "CC8"]]],
  ["ISO_42001", "A.6.2.6", [["EU_AI_ACT", "Art. 26"], ["EU_AI_ACT", "Art. 72"]]],
  ["ISO_42001", "A.6.2.7", [["EU_AI_ACT", "Art. 11"], ["EU_AI_ACT", "Art. 53"]]],
  ["ISO_42001", "A.6.2.8", [["EU_AI_ACT", "Art. 12"], ["SOC2", "CC7"]]],
  ["ISO_42001", "A.7.2", [["EU_AI_ACT", "Art. 10"]]],
  ["ISO_42001", "A.7.3", [["EU_AI_ACT", "Art. 10"], ["SOC2", "P3"]]],
  ["ISO_42001", "A.7.4", [["EU_AI_ACT", "Art. 10"], ["SOC2", "PI1"], ["SOC2", "P7"]]],
  ["ISO_42001", "A.7.5", [["EU_AI_ACT", "Art. 10"], ["EU_AI_ACT", "Art. 53"]]],
  ["ISO_42001", "A.7.6", [["EU_AI_ACT", "Art. 10"]]],
  ["ISO_42001", "A.8.2", [["EU_AI_ACT", "Art. 13"], ["EU_AI_ACT", "Art. 50"], ["EU_AI_ACT", "Art. 53"], ["SOC2", "P1"]]],
  ["ISO_42001", "A.8.4", [["EU_AI_ACT", "Art. 73"], ["SOC2", "P6"]]],
  ["ISO_42001", "A.9.2", [["EU_AI_ACT", "Art. 26"]]],
  ["ISO_42001", "A.9.4", [["EU_AI_ACT", "Art. 26"]]],
  ["ISO_42001", "A.10.3", [["SOC2", "CC9"]]],
  // EU -> SOC2
  ["EU_AI_ACT", "Art. 10", [["SOC2", "C1"], ["SOC2", "P3"], ["SOC2", "P4"]]],
  ["EU_AI_ACT", "Art. 12", [["SOC2", "CC7"]]],
  ["EU_AI_ACT", "Art. 14", [["ISO_42001", "A.8.2"]]],
  ["EU_AI_ACT", "Art. 15", [["SOC2", "CC6"], ["SOC2", "CC7"], ["SOC2", "A1"]]],
  ["EU_AI_ACT", "Art. 17", [["SOC2", "CC5"], ["SOC2", "CC8"], ["ISO_42001", "A.6.1.3"]]],
  ["EU_AI_ACT", "Art. 73", [["SOC2", "P6"]]],
  // Colorado SB 26-189
  ["COLORADO_AI", "CO-1", [["NIST_AI_RMF", "MAP 1"], ["NIST_AI_RMF", "MAP 2"], ["NEW_YORK_AI", "NY-1"]]],
  ["COLORADO_AI", "CO-2", [["EU_AI_ACT", "Art. 26"], ["EU_AI_ACT", "Art. 50"], ["ISO_42001", "A.8.2"], ["NEW_YORK_AI", "NY-4"]]],
  ["COLORADO_AI", "CO-3", [["NIST_AI_RMF", "GOVERN 5"], ["ISO_42001", "A.8.3"], ["NEW_YORK_AI", "NY-5"]]],
  ["COLORADO_AI", "CO-4", [["SOC2", "P5"], ["SOC2", "P7"]]],
  ["COLORADO_AI", "CO-5", [["EU_AI_ACT", "Art. 14"], ["NIST_AI_RMF", "MANAGE 2"], ["ISO_42001", "A.9.2"]]],
  ["COLORADO_AI", "CO-7", [["EU_AI_ACT", "Art. 13"], ["NIST_AI_RMF", "GOVERN 6"], ["ISO_42001", "A.10.3"]]],
  ["COLORADO_AI", "CO-8", [["SOC2", "CC8"], ["ISO_42001", "A.6.2.5"]]],
  ["COLORADO_AI", "CO-9", [["EU_AI_ACT", "Art. 12"], ["ISO_42001", "A.6.2.8"]]],
  ["COLORADO_AI", "CO-10", [["NIST_AI_RMF", "GOVERN 6"]]],
  ["COLORADO_AI", "CO-11", [["NIST_AI_RMF", "GOVERN 1"]]],
  // New York
  ["NEW_YORK_AI", "NY-1", [["NIST_AI_RMF", "MAP 1"]]],
  ["NEW_YORK_AI", "NY-2", [["NIST_AI_RMF", "MEASURE 2"], ["EU_AI_ACT", "Art. 10"], ["ISO_42001", "A.7.4"]]],
  ["NEW_YORK_AI", "NY-3", [["NIST_AI_RMF", "GOVERN 5"], ["EU_AI_ACT", "Art. 13"]]],
  ["NEW_YORK_AI", "NY-4", [["EU_AI_ACT", "Art. 26"], ["ISO_42001", "A.8.2"]]],
  ["NEW_YORK_AI", "NY-6", [["EU_AI_ACT", "Art. 50"], ["SOC2", "P1"]]],
  ["NEW_YORK_AI", "NY-7", [["EU_AI_ACT", "Art. 53"], ["NIST_AI_RMF", "GOVERN 1"]]],
  ["NEW_YORK_AI", "NY-8", [["EU_AI_ACT", "Art. 73"], ["NIST_AI_RMF", "MANAGE 4"], ["ISO_42001", "A.8.4"]]],
];

export const FRAMEWORK_CROSSWALK: CatalogCrosswalk[] = XW.flatMap(([fw, code, targets]) =>
  targets.map(([toFw, toCode]) => ({ from: { framework: fw, code }, to: { framework: toFw, code: toCode } }))
);

/** Stable lookup key for a control: `${framework}::${code}`. */
export function controlKey(framework: string, code: string): string {
  return `${framework}::${code}`;
}

/**
 * Validates the catalog's internal consistency. Throws if a crosswalk points
 * at a control that does not exist or links a framework to itself. Runs in
 * tests and in the SQL generator so a typo cannot ship as a silently-missing
 * row.
 */
export function assertCatalogIntegrity(): void {
  const keys = new Set(FRAMEWORK_CATALOG.map((c) => controlKey(c.framework, c.code)));
  if (keys.size !== FRAMEWORK_CATALOG.length) {
    throw new Error("Framework catalog has duplicate (framework, code) entries");
  }
  const seenPairs = new Set<string>();
  for (const xw of FRAMEWORK_CROSSWALK) {
    const a = controlKey(xw.from.framework, xw.from.code);
    const b = controlKey(xw.to.framework, xw.to.code);
    if (!keys.has(a)) throw new Error(`Crosswalk references unknown control ${a}`);
    if (!keys.has(b)) throw new Error(`Crosswalk references unknown control ${b}`);
    if (xw.from.framework === xw.to.framework) {
      throw new Error(`Crosswalk links ${a} within its own framework`);
    }
    const pair = [a, b].sort().join("<->");
    if (seenPairs.has(pair)) throw new Error(`Duplicate crosswalk pair ${pair}`);
    seenPairs.add(pair);
  }
}

// ─── Runtime sync (seeder / dev) ───────────────────────────────────────────

type CatalogClient = {
  frameworkControl: {
    upsert: (args: {
      where: { framework_code: { framework: ComplianceFramework; code: string } };
      update: { title: string; description: string; category: string; sortOrder: number };
      create: {
        framework: ComplianceFramework;
        code: string;
        title: string;
        description: string;
        category: string;
        sortOrder: number;
        builtIn: boolean;
      };
      select: { id: true };
    }) => Promise<{ id: string }>;
  };
  controlCrosswalk: {
    upsert: (args: {
      where: { fromControlId_toControlId: { fromControlId: string; toControlId: string } };
      update: Record<string, never>;
      create: { fromControlId: string; toControlId: string; note?: string };
    }) => Promise<unknown>;
  };
};

/**
 * Idempotently upserts the built-in catalog and crosswalk. Used by the demo
 * seeder; production relies on the migration. Returns a map of control key ->
 * id so callers can create mappings against the catalog.
 */
export async function syncFrameworkCatalog(db: CatalogClient): Promise<Map<string, string>> {
  assertCatalogIntegrity();
  const ids = new Map<string, string>();
  for (const control of FRAMEWORK_CATALOG) {
    const row = await db.frameworkControl.upsert({
      where: { framework_code: { framework: control.framework, code: control.code } },
      update: {
        title: control.title,
        description: control.description,
        category: control.category,
        sortOrder: control.sortOrder,
      },
      create: { ...control, builtIn: true },
      select: { id: true },
    });
    ids.set(controlKey(control.framework, control.code), row.id);
  }
  for (const xw of FRAMEWORK_CROSSWALK) {
    const fromControlId = ids.get(controlKey(xw.from.framework, xw.from.code))!;
    const toControlId = ids.get(controlKey(xw.to.framework, xw.to.code))!;
    await db.controlCrosswalk.upsert({
      where: { fromControlId_toControlId: { fromControlId, toControlId } },
      update: {},
      create: { fromControlId, toControlId, note: xw.note },
    });
  }
  return ids;
}
