import { prisma } from "./prisma";

/**
 * Source of truth for the Shadow AI denylist export.
 *
 * UrNammu does not sit in the network path, so a discovery marked BLOCKED is
 * only a label here. To make a block actually stop traffic, an external control
 * (DNS sinkhole, proxy ACL, firewall URL-list, CASB) consumes this denylist via
 * `GET /api/discovered-tools/blocklist` and enforces it. This module produces
 * the domain set and serializes it into the formats those controls expect.
 */

export type BlockedEntry = {
  domain: string;
  label: string;
  vendor: string | null;
  updatedAt: Date;
};

/**
 * Every BLOCKED discovery that carries a domain, deduplicated by normalized
 * domain. Tools blocked without a `detectedDomain` (e.g. manual reports with
 * only a name) can't be enforced by a network control and are omitted.
 */
export async function blockedDomains(): Promise<BlockedEntry[]> {
  const tools = await prisma.discoveredAITool.findMany({
    where: { status: "BLOCKED", detectedDomain: { not: null } },
    select: { detectedDomain: true, toolName: true, vendor: true, updatedAt: true },
    orderBy: { updatedAt: "desc" },
  });

  const seen = new Map<string, BlockedEntry>();
  for (const t of tools) {
    const domain = normalizeDomain(t.detectedDomain);
    if (!domain) continue;
    // First write wins — list is ordered newest-first, so we keep the most
    // recently updated record's metadata for a given domain.
    if (!seen.has(domain)) {
      seen.set(domain, {
        domain,
        label: t.toolName,
        vendor: t.vendor,
        updatedAt: t.updatedAt,
      });
    }
  }

  return [...seen.values()].sort((a, b) => a.domain.localeCompare(b.domain));
}

/**
 * Reduce a stored domain to a bare hostname: lowercase, trimmed, with any
 * scheme, path, port, or leading `*.`/`www.` removed. Returns null if nothing
 * usable remains.
 */
export function normalizeDomain(raw: string | null | undefined): string | null {
  if (!raw) return null;
  let d = raw.trim().toLowerCase();
  if (!d) return null;
  d = d.replace(/^[a-z]+:\/\//, ""); // strip scheme
  d = d.split("/")[0]; // strip path
  d = d.split(":")[0]; // strip port
  d = d.replace(/^\*\./, "").replace(/^www\./, ""); // strip wildcard / www
  d = d.replace(/\.$/, ""); // strip trailing dot
  return d || null;
}

export type BlocklistFormat = "text" | "hosts" | "json" | "pac";

export function parseFormat(value: string | null): BlocklistFormat {
  switch ((value ?? "").toLowerCase()) {
    case "hosts":
      return "hosts";
    case "json":
      return "json";
    case "pac":
      return "pac";
    default:
      return "text";
  }
}

/** Serialize the denylist into the requested format, with a content-type. */
export function serializeBlocklist(
  entries: BlockedEntry[],
  format: BlocklistFormat
): { body: string; contentType: string } {
  switch (format) {
    case "json":
      return {
        body: JSON.stringify(
          {
            generatedAt: new Date().toISOString(),
            count: entries.length,
            domains: entries,
          },
          null,
          2
        ),
        contentType: "application/json",
      };

    case "hosts":
      // Classic hosts-file sinkhole format (Pi-hole / pfBlockerNG adlists).
      return {
        body: entries.map((e) => `0.0.0.0 ${e.domain}`).join("\n") + "\n",
        contentType: "text/plain; charset=utf-8",
      };

    case "pac":
      return { body: toPacFile(entries), contentType: "application/x-ns-proxy-autoconfig" };

    case "text":
    default:
      // One bare domain per line — consumable by Squid `dstdomain`, dnsmasq,
      // NextDNS, and most firewall URL-list importers.
      return {
        body: entries.map((e) => e.domain).join("\n") + "\n",
        contentType: "text/plain; charset=utf-8",
      };
  }
}

/**
 * Proxy auto-config script that sinkholes blocked domains to a dead proxy
 * (`PROXY 0.0.0.0:0`) and sends everything else DIRECT. Matches the domain and
 * any subdomain via `dnsDomainIs` / suffix check.
 */
function toPacFile(entries: BlockedEntry[]): string {
  const domains = entries.map((e) => e.domain);
  return `// Generated by UrNammu Shadow AI blocklist
function FindProxyForURL(url, host) {
  var blocked = ${JSON.stringify(domains)};
  host = host.toLowerCase();
  for (var i = 0; i < blocked.length; i++) {
    var d = blocked[i];
    if (host === d || dnsDomainIs(host, "." + d)) {
      return "PROXY 0.0.0.0:0"; // dead proxy — connection fails
    }
  }
  return "DIRECT";
}
`;
}
