
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// NOTE: intentionally NO `datasource` block here. The datasource lives in
// schema.prisma (url = env("DATABASE_URL"), directUrl = env("DIRECT_URL")),
// where env() is a LAZY reference resolved when the client connects at
// runtime. Declaring datasource.url here is harmful:
//   - prisma/config's env() helper throws at config-load when the var is
//     absent (e.g. Vercel's dependency-install phase), breaking
//     `prisma generate` in postinstall.
//   - process.env.DATABASE_URL ?? "" resolves EAGERLY at generate time;
//     when the (Sensitive) var is absent at build it bakes an empty URL
//     into the generated client, which then fails at runtime with
//     "You must provide a nonempty URL".
// Letting the schema own the datasource keeps resolution lazy and correct
// for both `generate` (build) and the client (runtime).
// No `engine` / `datasource` keys: that's the "engine absent" config variant,
// which lets the schema's datasource (and its lazy env() references) drive
// both the CLI and the generated client. Setting engine: "classic" would
// make `datasource` mandatory, reintroducing the eager URL resolution this
// file is specifically avoiding.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
});
