/**
 * In-app help content. Mirrors the canonical authoring source under
 * `docs/help/*.md` so contributors can edit either place — the markdown files
 * are the source of truth, this map is the runtime bundle.
 *
 * GENERATED by scripts/gen-help-content.mjs — do not hand-edit the strings
 * below. Edit the matching `docs/help/<key>.md` and run `npm run help:sync`.
 */

export type HelpKey =
  | "dashboard"
  | "registry"
  | "registry-detail"
  | "agents"
  | "risk-center"
  | "compliance"
  | "shadow-ai"
  | "oversight"
  | "alerts"
  | "executive"
  | "reports"
  | "integrations"
  | "proxy-health"
  | "sensitive-scan"
  | "settings";

export const HELP_TITLES: Record<HelpKey, string> = {
  dashboard: "Dashboard",
  registry: "AI System Registry",
  "registry-detail": "System Detail",
  agents: "AI Agents",
  "risk-center": "Risk Center",
  compliance: "Compliance",
  "shadow-ai": "Shadow AI Discovery",
  oversight: "Oversight",
  alerts: "Alerts",
  executive: "Executive Dashboard",
  reports: "Reports",
  integrations: "Integrations",
  "proxy-health": "Proxy Health",
  "sensitive-scan": "Sensitive Scan",
  settings: "Settings",
};

export const HELP_CONTENT: Record<HelpKey, string> = {
  dashboard: `# Dashboard (Command Center)

The dashboard is your daily home screen for governance. Use it to triage open work across every system, agent, and alert.

## What you're looking at

- **Stat cards** — total systems, agents, high-risk systems, open alerts, shadow AI discoveries, and compliance rate. Each card is **clickable** and navigates to the relevant module page (Registry, Agents, Risk Center, Alerts, Shadow AI, or Compliance).
- **Executive posture chart** — rolling 12-month trend of approved systems vs. ungoverned discoveries.
- **Governance queue** — next-best actions pulled from every system in the registry (systems without assessments, pending approvals, expiring exceptions).
- **Segment risk heat maps** — risk breakdowns by department, vendor, and data sensitivity.
- **Remediation status** — clickable summary cards for open alerts, investigations, compliance issues, risk issues, renewal alerts, and ownership escalations. Each routes to the relevant page.
- **Automated governance recommendations** — AI-generated next-best-action suggestions per system, linked to the registry.

## Dashboard vs. Executive Dashboard

This page is a **working queue** — it exists to be cleared. The **Executive Dashboard** presents the same underlying data as a board-ready posture narrative with a weighted governance score and period-over-period deltas. Use this page to do the work; use that one to report on it.

## Where to start

- **Admins**: check **Settings → Provider Admin APIs** and **Settings → Shadow AI** first so telemetry and discovery are flowing. **Integrations** shows at a glance what is still unconnected.
- **Compliance officers**: work the governance queue top-down and triage open alerts.
- **Viewers**: browse the Registry and Risk Center to read the current state.

## Tips

- Click any stat card or remediation card to drill into that module.
- The **Needs Review** count only includes high-confidence \`DISCOVERED\` shadow-AI tools — low-confidence candidates have their own review queue.
- The **Executive posture chart** reflects overall compliance + risk + approval health; drift shows up here first.
- An empty **Telemetry** or cost figure usually means attribution headers are not reaching the proxy, not that nothing is being spent. **Proxy Health** will tell you whether the proxy is writing at all.
`,
  registry: `# AI System Registry

The registry is your central inventory of every managed AI system.

## Key actions

- **Register AI System** — opens the registration form. Fill owner, department, vendor, data sensitivity, review interval, and required approval stages.
- **Search & filter** — filter by name, department, vendor, risk level, and status.
- **Bulk actions** — archive or permanently delete (with typed-name confirmation).

## Lifecycle

A system moves through: \`DRAFT\` → \`UNDER_REVIEW\` → \`APPROVED\` → \`DEPLOYED\` → \`DEPRECATED\` → \`RETIRED\`. Status is updated automatically as governance reviews complete, or manually on the Edit page.

## Data sensitivity levels

- \`PUBLIC\` — non-sensitive public data.
- \`INTERNAL\` — employee-only operational data.
- \`CONFIDENTIAL\` — sensitive business data; restrict vendor data flows.
- \`RESTRICTED\` — regulated / high-sensitivity data. Exposure alerts will fire on telemetry.

## Approval stages

Toggle which stages must sign off before a system can move to \`APPROVED\`:

- **Owner** — the accountable product / business owner.
- **Security** — security team review.
- **Legal** — contract and regulatory review.
- **Compliance** — final compliance officer sign-off.

Leaving a stage off is appropriate for low-risk systems (e.g. internal copilots). High-sensitivity systems should require all four.
`,
  "registry-detail": `# System Detail

This page is the governance hub for a single AI system. Each tab represents a different dimension of governance, and the tab labels carry live counts so you can see where the work is without opening them.

## Tabs

- **Overview** — registered metadata and use case, the EU AI Act classification, the approval decision and staged review history, governance exceptions, evidence artifacts, incidents, telemetry attribution, and automated recommendations.
- **Agents (n)** — agents pointing to this system, with autonomy badges.
- **Risk (n)** — the risk profile, a dimension radar, a score-history trend chart, and open risk issues. Create a new assessment from here.
- **Compliance (n)** — assigned policies, compliance status, evidence text, and compliance issues, plus the **Framework Controls** card for control-by-control assessment against NIST AI RMF, ISO 42001, the EU AI Act and SOC 2. The **AI Assess** button runs automated gap analysis.
- **Audit Trail** — every recorded action on this system.

## Approval readiness

The **Approval Review** card lists exactly what is blocking approval. A system cannot move to \`APPROVED\` while any of these hold:

- No risk assessment on file.
- No governing policies assigned.
- A policy still in \`NOT_ASSESSED\`.
- A policy marked \`NON_COMPLIANT\` — remediate it or record an exception.
- A policy marked \`PARTIALLY_COMPLIANT\` with no evidence recorded.
- A policy marked \`COMPLIANT\` with no evidence text.
- A policy with a blocking rule violation.
- A required approval stage not yet granted.
- No next-review date set, or a next-review date in the past.
- An EU AI Act classification that identified a **prohibited practice** (Art. 5).

Two EU AI Act items are surfaced as warnings rather than hard blocks: a classification that has not been run yet, and a high-risk system with applicable articles still \`NOT_ASSESSED\`.

Note that both \`PARTIALLY_COMPLIANT\` and \`COMPLIANT\` require evidence. Marking a policy compliant without writing down why is treated as an unfinished assessment, not a pass — the rating alone is not the evidence.

Each blocker in the card deep-links to the place you resolve it.

## EU AI Act classification

The **EU AI Act Classification** card on the Overview tab shows the system's risk tier under Regulation (EU) 2024/1689 — \`PROHIBITED\`, \`HIGH_RISK\`, \`LIMITED_RISK\` or \`MINIMAL_RISK\` — your organisation's role (provider, deployer, or both), the flags that drive extra duties (Annex III area, Art. 6(3) derogation, Art. 27 FRIA, Art. 50 transparency, GPAI), and the applicable articles.

**Run classification** opens a short wizard: role, prohibited practices, Annex I products, Annex III use cases, the Art. 6(3) derogation, transparency triggers, general-purpose AI, and (for high-risk deployers) fundamental-rights impact triggers. The tier and article list update live as you answer; nothing is saved until the final step.

Saving does three things: stores the classification with its rationale and audit entry, creates a \`NOT_ASSESSED\` Framework Controls entry for every applicable EU AI Act article so it can be evidenced on the Compliance tab, and raises an alert for high-risk or prohibited outcomes.

## Compliance evidence

Evidence has two surfaces and both matter at approval time:

- **Assignment evidence** — the free-text field inside the Compliance status editor; explains **why** the status is what it is.
- **Evidence Artifacts** — structured records on the Overview tab (title, category, link, notes).

Good assignment evidence references specific controls (vendor SOC 2, DPIA on file, bias evaluation) rather than restating the policy.

## Telemetry attribution

The **Telemetry Attribution** card on the Overview tab shows usage and cost linked to this system. Attribution depends on the \`x-ai-system-id\` header reaching the proxy — an empty card usually means the header is not being sent, not that the system is unused. See **Settings → Proxy Setup**.
`,
  agents: `# AI Agents

Agents represent autonomous (or semi-autonomous) behavior layered on top of a system.

## When to register an agent vs. a system

- Register a **system** for the AI capability (e.g. "Claude-based support assistant").
- Register an **agent** when that capability runs autonomously with defined tools, triggers, or human-review rules. Agents link back to a parent system via **Connected Systems**.

## Autonomy levels

- \`FULL_AUTONOMY\` — agent acts with no human in the loop. Highest scrutiny.
- \`SUPERVISED\` — agent acts, but a human monitors and can intervene.
- \`HUMAN_IN_THE_LOOP\` — agent proposes; a human approves every action.
- \`HUMAN_ON_THE_LOOP\` — agent acts by default; a human may override during or after.
- \`MANUAL\` — human takes every action; the agent only assists.

## Human review triggers

JSON list of conditions that force a human step — e.g. "dollar amount > $1000", "contains PII", "new vendor". Feeds the AI risk review and shows on the agent detail page.

## MCP tool governance

The **MCP Tool Governance** card on the agent detail page shows which MCP servers the agent has declared and which tools its model actually invoked, as seen by the proxy. Traffic is attributed with the \`x-agent-id\` request header (the agent's id is shown on the card); \`x-ai-system-id\` still links usage to the parent system.

- **Allowed MCP servers** — server names, URL hosts, or wildcards such as \`*.example.com\`. Empty means observe only.
- **Allowed MCP tools** — \`tool\`, \`server/tool\`, or \`server/*\`. Empty means any tool on an allowed server.
- **Monitor** records a dry-run denial for unlisted servers and raises an alert for unapproved or never-seen tools, but forwards every request.
- **Enforce** returns \`403\` for unlisted servers and rewrites each server's \`allowed_tools\` so the provider only exposes allowlisted tools to the model.

**Approve** on an unapproved row adds it to the allowlist. **Oversight → MCP Activity** shows the same data across all agents.

## AI-assisted risk review

The **AI Agent Risk Review** card on the agent detail page shows two things side by side:

- A **heuristic** recommended risk level, computed locally from the agent's autonomy, capabilities, and connected systems. It is always present, with no AI call. A **Dedicated review suggested** badge appears when the heuristic thinks the agent warrants a full assessment.
- An **AI review**, produced on demand with **Generate AI Review** (**Refresh AI Review** once one exists). This calls the configured AI provider with the agent's capabilities, autonomy, triggers, and connected systems, and returns a recommended risk tier, written summary, concerns, and recommendations.

Both are starting points. The human reviewer makes the final call, and a formal risk assessment in the **Risk Center** is what actually sets the agent's recorded risk level.
`,
  "risk-center": `# Risk Center

Portfolio-level view of risk across every registered system.

## Reading the page

- **Risk counts** — systems grouped by \`CRITICAL\` / \`HIGH\` / \`MEDIUM\` / \`LOW\` / \`MINIMAL\`.
- **Reassessment alerts** — systems whose \`nextReviewDate\` is approaching or past.
- **Systems without assessments** — work queue for new registrations.
- **Risk heat map** — matrix of systems × dimensions, colored by score.
- **Distribution** — department and vendor breakdowns.
- **Control-gap detection** — systems flagged as high-risk but missing mitigating controls.

## The 6 risk dimensions

Each scored 0–100. Higher = more risk.

- **Bias** — fairness of outputs across groups.
- **Security** — vulnerability to attack or model misuse.
- **Privacy** — exposure of personal or restricted data.
- **Fairness** — outcome equity and disparate impact.
- **Performance** — reliability and accuracy.
- **Transparency** — explainability and traceability.

Each score requires a justification so later reviewers can re-evaluate it.

## Running an assessment

Pick a template (Copilot / Vendor AI SaaS / Autonomous Agent / Customer-Facing AI) → score the dimensions or click **AI Suggest** → answer branching questions → review control gaps → save. The system's overall risk level updates automatically.

## Reassessment cadence

\`reviewIntervalDays\` on each system controls how often a re-assessment is required. Alerts fire ahead of the due date; overdue reviews escalate automatically.
`,
  compliance: `# Compliance

Manage policies, assignments, and the audit trail.

## Policies

Each policy belongs to a framework — \`EU_AI_ACT\`, \`NIST_AI_RMF\`, \`ISO_42001\`, \`SOC2\`, or \`CUSTOM\` — and has two parts:

- **Content** — long-form policy text.
- **Rules (JSON)** — machine-evaluable constraints: allowed/blocked vendors, max data sensitivity, required approval stages, max review interval, minimum risk level, model name patterns.

## Enforcement

Two different things are called "enforcement" here, and it is worth keeping them apart.

**At approval time**, a policy's enforcement level decides whether it can hold a system back:

- \`ADVISORY\` — violations are flagged but do not block approval.
- \`BLOCKING\` — violations hard-block the system from moving to \`APPROVED\`.

**At request time**, the proxy can evaluate the same machine-readable rules against live traffic. The mode is global, set at **Settings → General**:

- **Off** — the proxy ignores policies and requests always pass through. Safe default.
- **Dry run** — the proxy evaluates policies and records denial events, but still forwards the request. Use this to tune rules before turning enforcement on.
- **Enforce** — the proxy returns \`403\` on a blocking violation and the request never reaches the upstream provider.

Go through dry run first. It gives you the full denial record you would have produced, with none of the breakage.

## Assignments

A \`PolicyAssignment\` links a policy to a system with a compliance status:

- \`COMPLIANT\` — system fully meets policy requirements.
- \`PARTIALLY_COMPLIANT\` — meets some; a remediation plan is expected.
- \`NON_COMPLIANT\` — does not meet; remediate or request an exception.
- \`NOT_ASSESSED\` — has not been evaluated yet.

Approval requires every assignment to be out of \`NOT_ASSESSED\` and \`NON_COMPLIANT\`.

## AI gap analysis

**AI Assess** on an assignment calls the configured AI provider with policy rules + system metadata + existing evidence, and creates structured \`ComplianceIssue\` records (severity, title, detail, remediation).

## Blocked Queries

**Compliance → Blocked Queries** is the denial log — every request the proxy evaluated as a policy violation, in both dry-run and enforce modes. Open a denial to see which rule matched and the request metadata behind it.

Read this page alongside the enforcement mode: in dry run, entries are requests that **would** have been blocked, and are your tuning signal. In enforce, they are requests that actually failed, and someone may be waiting on one.

## Framework controls

**Compliance → Framework Coverage** (and the **Framework Controls** card on a system's Compliance tab) works from a seeded catalog of controls per framework: the 19 NIST AI RMF categories, the 38 ISO/IEC 42001 Annex A controls, the EU AI Act articles that carry provider or deployer obligations, and the SOC 2 trust services criteria.

- Assess a system control by control. Each rating is a \`ComplianceMapping\` row with its own evidence text.
- A control marked \`COMPLIANT\` also satisfies its **crosswalked** peers in the other frameworks, shown as **Inherited**. Inheritance is one hop and only from a direct \`COMPLIANT\` rating — a partial rating does not propagate.
- **Coverage** is compliant plus inherited controls as a share of the framework. Partial ratings show separately so the gap stays visible.
- **AI Gap Analysis** sends the current statuses to the configured AI provider and returns prioritised gaps. It is advisory: nothing is saved until you record a rating.

The org-wide page rolls this up per framework. A system is **in scope** for a framework once it has at least one direct rating there.

## Services

**Compliance → Services** groups services by their current compliance status across all assigned policies — the fastest way to see what is \`NON_COMPLIANT\` or still \`NOT_ASSESSED\` without walking the registry system by system.

## Audit trail

**Compliance → Audit Trail** shows every governance action. Filter by actor, action, entity type, or date. Export as JSON or CSV for external auditors.
`,
  "shadow-ai": `# Shadow AI Discovery

Detect AI tools in use in your organization that are not yet in the Registry.

## Discovery sources

Four scanning sources, each independently configurable:

- **Google Workspace** — scans OAuth activity logs for AI apps that users have connected.
- **Microsoft 365** — scans delegated app permissions in your tenant against a known-AI-tools registry. Resolving who granted each permission to an email address needs \`User.Read.All\` on the scanning app; without it the tool is still discovered but its user list stays empty.
- **Hexnode UEM** — reads the app inventory from managed devices, catching desktop and mobile apps that never touch an OAuth flow.
- **CrowdStrike Falcon** — endpoint discovery, for AI tools observed running on protected hosts.

Plus two import paths that need no live connection:

- **DNS / proxy logs** — CSV or TXT upload, or JSON API ingestion, of network-observed AI domains. The importer reads native gateway exports: pick the vendor (Cisco Umbrella, Cloudflare Gateway, Zscaler, Netskope, Prisma Access, DNSFilter, NextDNS, or generic) and it maps that vendor's domain, user, department, count, and timestamp columns. Hostnames are normalized before matching, so \`api.openai.com\`, \`openai.com.\`, and mixed-case variants resolve to the same tool.
- **Netskope** — a dedicated import for Netskope's cloud log shipper.

The identity-based sources (Google, Microsoft) only see apps federated to your IdP. A tool someone signed into with a personal account is invisible to them and must be caught by device inventory or network logs — which is why the sources are complementary rather than redundant.

## Observation details

Each discovered tool records what the scans actually observed, shown under the tool name:

- **First seen / Last seen** — the earliest and latest observation across every scan. Log imports use the export's own timestamp column when it has one (\`timestamp\`, \`@timestamp\`, \`time\`, \`date\`, and similar; ISO or epoch); otherwise the import time is used.
- **Users** — the email addresses seen using the tool, as chips. Only real email addresses are kept; device names or bare usernames from network logs count toward the user total but are not listed.
- **Departments** — when a directory sync is enabled (**Settings → Users & Identity**), the observed users are rolled up by their directory department, for example "Engineering 4 · Sales 2". Email aliases fold onto the same person first, and users with no directory match (or no department) are counted as unmatched.
- **OAuth scopes** — the permissions granted to the app, for identity-provider sources.

The **user count** follows one rule: a rescan from the **same** source replaces the count, so it can go down when access is revoked or devices are retired; a **different** source only ever raises it, so two partial views combine as a maximum rather than overwriting each other.

## Confidence scoring

Every discovered tool is assigned a match confidence based on how it was identified:

- **High** (score 10+) — strong match via domain + name or multiple signals.
- **Medium** (score 6–9) — partial match via name or publisher only.
- **Low** (score < 6) — heuristic match via AI keywords (e.g. ".ai" domain, "gpt", "copilot") but no known registry entry.

## Page sections

The page splits discoveries into three sections:

- **Needs Review** — high-confidence matches and legacy tools. These are confirmed AI tools that need a governance decision: **Convert to Governed System**, **Register & Assess**, **Approve**, or **Block**.
- **Low-Confidence Candidates** — medium and low-confidence matches. Each shows a confidence badge, score, and match reasons. Actions: **Promote** (move to main queue as high-confidence) or **Dismiss** (permanently suppress with a reason).
- **Resolved** — tools that have been registered, approved, or blocked.

## Scan triggers

- **Manual**: click **Scan All Sources**. Every configured source runs; unconfigured ones are skipped cleanly and reported as such, so it is always clear which sources actually ran.
- **Automatic**: configured in **Settings → Shadow AI** (cron fires hourly; each source checks its own interval).

## What "Block" actually does

Blocking records the decision in UrNammu — but UrNammu is not in your traffic path, so the block only takes effect through one of two enforcement layers:

- **Network** — blocked domains are published on an authenticated feed at \`/api/discovered-tools/blocklist\`, which a DNS sinkhole, proxy ACL, firewall URL list, or CASB polls to enforce. Formats: \`text\` (default), \`hosts\`, \`json\`, and \`pac\`, selected with \`?format=\`. The feed requires a Bearer token and fails closed — with no token configured it returns 503 rather than serving unauthenticated. Set the token in **Settings → Shadow AI**.
- **Identity** — where the tool is federated to Google Workspace or Microsoft 365 and the scan captured an app handle, blocking disables the app at the identity provider so sign-ins stop. Tools discovered without an app handle report \`skipped\`; a provider missing the required admin permission reports \`failed\`.

Check **Settings → Shadow AI** for a readiness summary of both layers. A blocked tool with neither layer configured is a documented decision, not an enforced one.

## Automatic suppression

Discoveries whose name (and vendor, when present) match an existing Registry system are auto-linked and suppressed. Dismissed candidates are also suppressed — the scanner checks the dismissed list before creating new records.
`,
  oversight: `# Oversight

Provider-level usage, cost, anomaly, vendor, and investigation telemetry.

## How provider sync works

With an Anthropic admin key, an OpenAI admin key, a Cursor admin key, and/or Google Gemini billing export configured in **Settings → Provider Admin APIs** (gateway keys live under **Settings → Integrations**), each provider has its own hourly cron that syncs once that provider's own interval has elapsed since its last successful run, and writes into:

- \`UsageBucket\` — tokens / requests per provider / model / project / actor / time bucket.
- \`CostBucket\` — amount and line-item cost, with the same attribution columns as \`UsageBucket\` (API key, workspace, governed system).
- \`AssistantDailyStat\` — one row per person per day for the coding assistants (Claude Code via the Anthropic Admin API analytics report, Cursor via the Cursor Admin API): sessions, requests, lines added / removed / accepted, commits, PRs, tool accept / reject, tokens, and cost as real columns rather than JSON.
- \`ProviderProject\` / \`ProviderActor\` — workspaces (Anthropic Console workspaces, OpenAI projects, LiteLLM teams) and members discovered upstream.
- \`ProviderSyncRun\` — a record of each sync attempt.

**If a provider's admin key is not configured, that provider is skipped cleanly** — no sync-run row, no upstream call. The manual-sync panel reports this as "Skipped (not configured): …" so it is clear which providers are actually active.

What each sync records, beyond the shared bucket shape:

- **Anthropic** — organization usage per model, API key, and workspace; cost per workspace, model, and cost type (the cost report has no API-key dimension, so Anthropic spend is attributed at workspace granularity); the workspace list; plus the Claude Code analytics feed (sessions, lines, commits, estimated cost per developer) that backs Usage by Person when a machine is not instrumented with OTel.
- **OpenAI** — usage per model and project, including prompt-cache hits as \`cacheReadTokens\`, and request counts. Usage and cost results are paginated; if the page cap is hit the sync-run metadata records \`truncated: true\` so a partial day is never mistaken for a quiet one.
- **Cursor Admin API** — per-user, per-day requests, tokens, accepted lines, and charged spend. This is where Cursor tokens and cost come from; the Cursor OTel hook carries neither.
- **Portkey** — one usage and cost bucket per day per model, and one usage bucket per day per user. Portkey reports cost in cents; the sync divides by 100 and records a \`reconciliation\` block in the sync-run metadata comparing the org-level graph total with the summed per-model and per-user totals so the unit assumption is auditable.
- **Gemini** — spend and best-effort project attribution from the BigQuery billing export.

Because every provider runs in its own function, a slow or failing provider does not delay the others, and one healthy provider cannot reset the clock for a stalled one. **Settings → Provider Admin APIs** shows each provider's last run, its outcome, and when it is next due.

## Pages

- **Overview** — totals, breakdowns, top cost drivers, anomaly findings, and two attribution panels: **Cost by Governed System** (spend per registered AI system, with the attributed share of total spend and an unattributed remainder) and **Cost by API Key** (per-key spend where the provider reports it; Anthropic rows are workspaces). Both read the mapping configured under **Settings → Provider Admin APIs → Usage Attribution**: a default system per provider plus per-key overrides, applied to usage and cost alike on the next sync.
- **Usage** — drill into normalized buckets; link usage to a system for attribution.
- **Vendors** — vendor profiles with contract lifecycle, security review, data residency, subprocessors, approved use cases.
- **Investigations** — follow-up queue for alerts and incidents.
- **Provider Posture** — side-by-side provider comparison: cost, tokens, incidents, risk tier.
- **Provider Security** — audits each configured provider's secure-use and privacy configuration: credentials, encryption, data retention, training-on-data, residency, and vendor governance.

## Per-surface developer-AI dashboards

One page per AI surface, because the telemetry each one emits is different:

- **Claude Platform** — Anthropic Console / API usage, cost, and access, from the Anthropic Admin API sync. Includes active API keys and organization members. Last 30 days.
- **Claude Code** — per-user developer productivity and usage from live OpenTelemetry data. Last 7 days. People with no OTel data are filled in from the Anthropic Admin API analytics sync and marked "est." Has two drilldowns: an **Audit Log** of per-event records, and **Session Traces** (below).
- **Cowork** — productivity, cost, and governance metrics for Claude Cowork (Claude Desktop VM) sessions, from OTel. Last 7 days.
- **Cursor** — developer activity from Cursor via OTel spans. Last 7 days. **Cursor's hook carries no token or cost data**, so the span metrics are activity only; spend and per-user lines come from the Cursor Admin API sync when its team key is configured — do not read the absence of spend here as zero spend.

## Usage by Person

**Oversight → Usage by Person** answers "who is using what, and what does it cost?" with one row per human across every surface UrNammu observes:

- **Claude Code** and **Cowork** — live OTel metrics (Cowork is the Claude Desktop \`local-agent\` surface; everything else counts as Claude Code, so the two never overlap). When a person has no OTel data, the Anthropic Admin API analytics sync (\`AssistantDailyStat\`) fills in sessions, lines, commits, and an estimated cost, marked "est."
- **Cursor** — the Cursor Admin API sync (\`AssistantDailyStat\`). Active days count only days Cursor marks the seat active. Per-user spend comes from the usage-events feed; when that feed returned nothing for the synced window, Cursor cost shows as "n/a" rather than zero.
- **API (proxy)** — Anthropic and OpenAI calls through the governance proxy, attributed by the \`x-user-email\` header, with a count of flagged requests.

People are matched by lower-cased email. When a **directory sync** is enabled (**Settings → Users & Identity**), every observed email is first resolved through the directory's alias map, so a person seen as \`ada.lovelace@\` in Cursor and \`ada@\` through the proxy is one row keyed by their directory primary address; name and department then come from the directory. Without a directory, name and department come from the UrNammu user profile when one exists, otherwise from the provider's member directory. Each row also carries a directory status — \`active\`, \`deactivated\`, or \`unknown\` (no directory match) — and deactivated accounts that still show usage get a **Deactivated** badge; the CSV includes the status as a column. Anything without an email identity (anonymous proxy calls, API-key actors, un-tagged OTel clients) is kept out of the table and totalled in the **Unattributed cost** card so totals stay honest. Anthropic Console usage is reported per API key, not per person, and is intentionally excluded — see **Claude Platform** for that view.

Pick a **7 / 30 / 90-day** window, search by name, email, or department, click a surface chip to open that dashboard filtered to the person, or **Download CSV** for the full column set. **Save as report** (\`ADMIN\` / \`COMPLIANCE_OFFICER\`) creates a report from the **Usage by Person** template so the view can be exported as PDF/CSV/JSON and scheduled for email delivery.

## Session traces

**Oversight → Claude Code → Session Traces** reconstructs a session as turns, model calls, and tool use in execution order, rendered as a waterfall.

Spans are **derived from event timing**, not emitted as spans by the client — so treat durations as close approximations rather than instrumented measurements. Long idle gaps are compressed in the rendering so a session with a lunch break in the middle stays readable; each span carries a status of \`ok\`, \`error\`, \`denied\`, or \`flagged\`.

Traces cover a 30-day window and are metadata only — no prompt text and no code content, on this page or in the audit log.

## Dangerous prompt monitoring

When traffic flows through the proxy, prompts are scanned for 5 risk categories: prompt injection, secret extraction, data exfiltration, malware/phishing generation, and dangerous autonomy. Findings appear as structured alerts with matched signals, sanitized excerpts, and related usage logs. False positives can be marked with exceptions that suppress similar future alerts.

## Proxy attribution

Proxy traffic is attributed via optional headers: \`x-user-email\` (per-user cost tracking), \`x-department\` (cost center), \`x-ai-system-id\` (link to registry), and \`x-agent-id\` (link to a registered agent, which also enables MCP tool governance). Configure these in **Settings → Proxy Setup**.

## Proxy token accounting

Every proxy path (Vercel and Azure, Anthropic and OpenAI) records the same four token buckets, so proxy rows and admin-sync rows add up the same way:

- \`inputTokens\` is **all** input the provider processed: uncached + cache read + cache creation. \`cacheReadTokens\` and \`cacheCreationTokens\` are the breakdown, not extra tokens on top.
- Cost is uncached × input price + cache read × cache-read price + cache creation × cache-write price + output × output price, from one pricing table matched by exact model id first, then model family.
- A model missing from the pricing table is **never charged a default**. Its cost is stored as 0 and the usage row's metadata carries \`pricingMatched: false\`, so unpriced models are visible rather than silently mispriced.
- OpenAI streaming responses now record usage too (the proxy asks OpenAI for the trailing usage chunk when the client did not) and run response DLP like non-streaming calls.
- Anthropic \`count_tokens\` and \`batches\` calls pass through the proxy without producing usage rows.

## MCP Activity

**Oversight → MCP Activity** lists every MCP server agents declare and every tool the model invokes through the proxy, with the allowlist verdict for each. Tools invoked outside an agent's allowlist appear under **Needs a decision**; open the agent to approve them or tighten the allowlist.

## Spend budgets

Create a budget by **provider**, **system**, or **department**. Monthly budget + warning threshold % (default 80%). Crossing the threshold raises a \`cost_anomaly\` alert.

## Anomaly detection

Thresholds live in **Settings → Provider Admin APIs**: recent vs. baseline windows, min token/cost thresholds, per-dimension sensitivity multipliers. When recent usage exceeds baseline × multiplier, a \`cost_anomaly\` or \`model_drift\` alert fires.
`,
  alerts: `# Alerts

Centralized alert inbox for governance signals.

## Lifecycle

\`OPEN\` → \`ACKNOWLEDGED\` → \`RESOLVED\` / \`DISMISSED\`

- **Acknowledge** — marks as seen / being worked.
- **Create Investigation** — opens an Investigation pre-linked to this alert.
- **Resolve** — addressed.
- **Dismiss** — not a real issue (for non-prompt-risk alerts).
- **False Positive** — for dangerous prompt alerts only. Requires a reason and optionally creates suppression exceptions.

## Alert sources

- \`policy_violation\` — a policy rule evaluated to a violation.
- \`risk_reassessment\` — a system's \`nextReviewDate\` is approaching or overdue.
- \`discovery\` — new shadow-AI tool discovered.
- \`compliance_gap\` — AI compliance analysis found a gap.
- \`incident\` — a governance incident was opened.
- \`renewal\` — vendor contract renewal is approaching.
- \`escalation\` — a review is overdue past the escalation threshold.
- \`model_drift\` — usage pattern deviates from baseline.
- \`data_exposure\` — restricted-sensitivity data observed in provider telemetry.
- \`cost_anomaly\` — spend crossed a budget or anomaly threshold.
- \`ownership_escalation\` — system has no owner assigned.
- \`dangerous_prompt\` — proxy-scanned traffic matched a risky prompt pattern.
- \`key_usage_rule\` — an API key's usage tripped a key usage rule.

## Dangerous prompt alerts

When traffic flows through the proxy, prompts are analyzed for jailbreak attempts, credential extraction, data exfiltration, malware generation, and unsafe autonomy patterns. These alerts show structured investigation detail:

- **Provider & model badges** — which AI provider and model were used.
- **Category badges** — which risk rules triggered, color-coded by severity.
- **Matched signals** — the exact phrases that matched, shown as code elements.
- **Sanitized excerpt** — a redacted snippet of the prompt text (full prompts are never stored).
- **Related usage logs** — expandable panel showing flagged API calls near the alert.

## False positive marking

If a dangerous prompt alert is benign (e.g. legitimate security testing), click **False Positive**:

- Enter a reason explaining why it is a false positive.
- Optionally check **Create exception** to suppress similar future alerts for the matched categories.
- The alert is dismissed and tagged with a "False Positive" badge.

Manage exceptions at **Alerts → Manage prompt risk exceptions**. Exceptions can be deactivated or reactivated. The system only suppresses alert creation — usage is still logged for audit.

## Tuning the detection engine

The dangerous-prompt engine is rule-based and fully tunable at **Alerts → Tune detection rules**. Each rule has:

- A stable **key** (\`prompt_injection\`, \`secret_extraction\`, etc.) — this is the identifier referenced by exceptions, so it is **immutable** once created.
- A **label** and optional **description**.
- A **severity** — \`critical\` → CRITICAL alerts, \`warning\` → HIGH alerts.
- Up to 10 **regex patterns**, matched case-insensitively against user-authored prompt text only (assistant, tool, and system content are never scanned).

Five built-in rules are seeded on install. Built-ins can be edited, disabled, or reset to their original definition, but cannot be deleted. Custom rules can be created with fresh keys and deleted when no longer needed.

Patterns are validated on save: they must compile as JavaScript regex, fit within 500 chars, and not contain obvious ReDoS shapes (e.g. \`(.*)+\`). A short probe string is run against each pattern; patterns that take more than 50 ms are rejected.

Use the **Test a prompt** panel on the rules page to dry-run a prompt against the current enabled ruleset without creating an alert. Rule changes take effect within 30 seconds (runtime cache) or immediately on mutation.

## Key usage rules

Where dangerous-prompt rules inspect **what** is being asked, key usage rules watch **how a credential behaves**. Manage them at **Alerts → Key usage rules**. Each rule evaluates provider telemetry per API key and raises a \`key_usage_rule\` alert.

Seven condition types are available:

- \`VOLUME_THRESHOLD\` — absolute tokens, cost, or requests over a window past a ceiling.
- \`SPIKE_MULTIPLIER\` — a recent window compared against the immediately preceding baseline window.
- \`NEW_KEY\` — a key seen for the first time, with non-trivial volume.
- \`DORMANT_REACTIVATION\` — a key idle for N days that started transacting again.
- \`OFF_HOURS\` — activity outside declared business hours and days. Requires hourly buckets.
- \`MODEL_ALLOWLIST\` — a key used a model outside its allowlist.
- \`FAN_OUT\` — a key suddenly spanning more distinct projects or actors than expected.

Eight rules ship enabled by default, covering spend spikes, token spikes, a daily spend ceiling, first-time key activity, dormant reactivation, off-hours use, non-approved models, and project fan-out.

Rule keys are **immutable** once created, because alert dedupe references them. Built-in rules can be edited, disabled, or reset to their original definition; custom rules can be created and deleted freely.

Use **Preview** before enabling a rule — it dry-runs the config against recorded telemetry and reports the findings it **would** have raised plus how many keys were evaluated. It writes nothing: no alerts, no profile updates. This is the fastest way to catch a threshold that would bury you in alerts. **Reset** restores a built-in to its shipped defaults.

Off-hours rules carry an explicit timezone offset and business-day list. Set these deliberately: the default will not match a distributed team, and a mis-set timezone makes every normal working day look like off-hours activity.

## Severity

\`CRITICAL\` / \`HIGH\` / \`MEDIUM\` / \`LOW\` / \`INFO\` — drives the badge color and sort order.
`,
  executive: `# Executive Dashboard

A board-ready posture overview. Where the **Dashboard** is a working queue, this page is the narrative you take into a governance review or board meeting.

## Governance score

A single 0–100 score, computed as a weighted blend of five dimensions:

- **Compliance** (25%) — share of policy assignments in a compliant state.
- **Risk Posture** (25%) — distribution of system risk levels across the portfolio.
- **Governance Coverage** (20%) — how much of the registry has assessments, owners, and approvals on file.
- **Shadow AI** (15%) — unresolved discoveries relative to governed systems.
- **Incident Health** (15%) — open incidents and critical alerts in the period.

Because the dimensions are weighted, a strong compliance rate will not hide a growing shadow-AI backlog — each dimension is also shown on its own so you can see which one is dragging the score.

## Board metrics

Six headline figures, each with a period-over-period delta: **Governance Score**, **Compliance Rate**, **Avg Risk Score**, **Monthly Spend**, **Shadow AI Backlog**, and **Open Incidents**.

Deltas compare the selected period against the immediately preceding one of equal length, so a "improving" arrow always means improving **relative to last period**, not against an absolute target.

## Posture narrative

A written summary generated from the metrics — what moved, by how much, and the likely driver. Use it as the starting point for a governance update rather than a final draft; it describes the numbers but does not know your organization's context.

## Charts

- **12-Month Posture Trend** — rolling monthly governance score, so drift is visible before it becomes a finding.
- **Risk by Department** and **Risk by Vendor** — the same heat maps as the Dashboard, included here so a single export covers the whole story.

## Notes on the numbers

- Spend figures deduplicate proxy traffic against provider-reported usage, so a request logged by both the proxy and a provider admin API is counted once.
- Systems are counted as of the period end, so retroactively registering a system changes historical counts.
- The score is recomputed on each page load; it is not snapshotted. Use **Reports → Executive Summary** if you need a fixed artifact for a specific date.
`,
  reports: `# Reports

Build, export, and schedule custom reports across your governance data. Authoring requires \`ADMIN\` or \`COMPLIANCE_OFFICER\`. Any signed-in user can open a report marked \`SHARED\`.

## Starting from a template

Ten templates cover the common asks: **Usage by Person**, **Cost by Department**, **Risk Posture**, **Compliance Status**, **Usage & Cost**, **Shadow AI Inventory**, **AI System Inventory**, **Executive Summary**, **Alerts Activity**, and **Audit Trail**. A template is a starting configuration, not a fixed format — every column, filter, and grouping stays editable afterward.

## Data sources

Each report draws from exactly one source:

\`AI Systems\` · \`AI Agents\` · \`Risk Assessments\` · \`Compliance\` · \`API Usage & Cost\` · \`Alerts\` · \`Shadow AI\` · \`Audit Log\` · \`Usage by Person\`

Columns are typed — string, enum, number, or date — and the builder offers filters appropriate to the type. Numeric columns on assessment and cost sources can be aggregated (for example, average risk score by department) rather than listed row by row.

**Usage by Person** is a computed source: one row per person with their Claude Code, Cowork, Cursor, and proxied-API cost and activity merged by email (the same data as **Oversight → Usage by Person**). Every column can be filtered, sorted, and grouped — group by **Department** to get spend per team — and the date range sets the activity window.

## Building a report

Pick a data source → choose columns → add filters → shape the output (grouping, sorting, limits) → preview. The **Preview** tab runs the real query against live data, so what you see is what a scheduled run will produce.

## Report detail tabs

- **Preview** — current output, re-queried on load.
- **Run history** — every past run with its artifact, so you can show an auditor the figures as they stood on a given date.
- **Schedules** — recurring delivery, described below.

## Export formats

\`PDF\` for circulation, \`CSV\` for spreadsheet analysis, \`JSON\` for downstream tooling. PDF renders the shaped and grouped layout; CSV and JSON carry the underlying rows.

Stored run artifacts are capped at 5 MB. A larger run still succeeds and still downloads, but is not persisted for later re-download from **Run history** — narrow the filters or the date range if you need the artifact kept.

## Scheduled delivery

Schedules run \`DAILY\`, \`WEEKLY\`, or \`MONTHLY\` and email the chosen format to a recipient list. Email delivery must be configured first at **Settings → Reporting**; without it, schedules save but never send.

A scheduled run queries data at send time, so a monthly report reflects the month it was sent, not the month it was authored. Use **Run history** to compare successive periods.

## Access

Each definition is either \`PRIVATE\` or \`SHARED\`. \`PRIVATE\` is visible to its owner and to \`ADMIN\`; \`SHARED\` is visible to every signed-in user. Editing and deleting stay with the owner and with any \`ADMIN\` or \`COMPLIANCE_OFFICER\`.

Deleting a definition also removes its run history and any schedules attached to it.
`,
  integrations: `# Integrations

Every external service UrNammu connects to, on one page, grouped by purpose. Requires \`ADMIN\`.

Each tile shows whether the service is connected, and each group header shows a connected count (e.g. "2/4 connected"). Click a tile to configure credentials and sync options inline; identity and discovery tiles link out to the settings page where their full auth or scan configuration lives.

## Categories

- **AI Models** — the internal AI provider used for in-app features (risk suggestion, compliance gap analysis, agent risk review, summarization).
- **Provider Telemetry** — Anthropic Admin API (organization usage plus the Claude Code analytics feed), OpenAI Admin API, and Google Cloud Billing (Gemini). These feed Oversight usage and cost. The **Cursor Admin API** is the fourth provider sync — it supplies Cursor tokens, requests, and per-user spend — and is configured under **Settings → Provider Admin APIs** rather than as a tile here.
- **AI Gateways** — OpenRouter Activity, Helicone Requests, Portkey Analytics, and LiteLLM Proxy. Use these when traffic already flows through a gateway and you want its records without re-routing through the UrNammu proxy.
- **Identity** — Google Sign-In and Microsoft 365 Sign-In, for authenticating users into UrNammu.
- **Directory Discovery** — Google Workspace and Microsoft 365 Tenant Apps, for Shadow AI scanning of connected third-party apps.
- **Observability** — Azure Monitor (feeds the Proxy Health board) and Datadog.

## Integrations vs. Settings

This page is a catalog: it answers "what are we connected to, and what is still unconfigured". The **Settings** pages are the authority for behavior — scan intervals, anomaly thresholds, attribution headers, and roles. A tile that reports "connected" only means credentials are present and valid-looking; it does not mean a sync has succeeded. Check **Oversight** or **Settings → Provider Admin APIs** for sync-run results.

## Credential handling

Secrets entered here are encrypted at rest with \`SETTINGS_ENCRYPTION_KEY\` and are masked when read back — the UI shows whether a value exists, never the value. Values set in the UI take precedence over environment variables; env vars are the fallback when the database value is absent.
`,
  "proxy-health": `# Proxy Health

Live-ops board for the AI proxy. Use it to answer "is the proxy up and writing?" before investigating a gap in Oversight data.

## Heartbeat tiles

These refresh every 15 seconds and are computed from what the proxy has actually written to the database:

- **Heartbeat Age** — how long since the most recent usage log was written. This is the single most useful field on the page: if it is minutes old under normal traffic, the proxy is not reaching the database.
- **Proxy Writes** — usage-log rows written in the current window.
- **Flagged** — of those, how many tripped prompt-risk detection.
- **Policy Denials** — denials recorded in the same window.
- **Window** — the interval the tiles are summarizing.

A genuinely quiet period looks identical to an outage on these tiles. Confirm against expected traffic before escalating.

## Azure Monitor metrics

Optional, and refreshed on its own schedule rather than on the 15-second poll. When an Azure Monitor connection is configured, a scheduled sync runs every 15 minutes and the **Sync now** button runs the same sync immediately. The board pulls the function app's own platform metrics — **Invocations**, **Error Rate**, **Avg Response**, and a 2xx / 4xx / 5xx breakdown — over the last 15-minute window.

The card header shows **Last synced N min ago** so you can tell whether the scheduled sync is keeping up. It stays neutral while the newest snapshot is under about 35 minutes old, turns amber once a scheduled run appears to have been missed, and turns red after an hour without a snapshot. A red indicator with a healthy heartbeat means the sync job is broken, not the proxy: check that \`/api/cron/proxy-health\` is scheduled and that \`CRON_SECRET\` is set.

This is the half of the picture the heartbeat tiles cannot see: invocations that failed **before** writing anything. Invocations arriving but no proxy writes landing usually means a database or credential problem inside the proxy; no invocations at all points upstream, at routing or client configuration.

## Recent proxy writes

The ten most recent usage logs, with **Time**, **Status**, **User**, **Dept**, **Tokens**, and **Cost**. Rows are labeled **Flagged** or **Blocked** where they apply, and failures are distinguished as **Proxy error** or **Upstream error** — the former is yours to fix, the latter is the provider's.

Use this table to confirm attribution headers are populated. Rows with no user or department mean \`x-user-email\` and \`x-department\` are not being sent; configure them in **Settings → Proxy Setup**.

**Tokens** counts all input tokens (uncached plus cache read and cache creation) and output. A row with tokens but a **Cost** of $0 on a real model usually means the model is not in the pricing table — the row's metadata will carry \`pricingMatched: false\`. Unknown models are never charged a default price.

## Sync errors

If the last Azure Monitor sync failed, the metrics card reports **Last sync failed** with the error from Azure; a connection that has never run shows **Never synced**. Scheduled and manual syncs both record a snapshot whether they succeed or fail, so the **Last hour of syncs** table shows every attempt. Neither state affects proxy operation or logging — they only mean this board cannot show platform metrics right now.

## When configuration is missing

Azure Monitor requires a subscription ID, resource group, and function app name. Without all three the metrics card reports that it is unconfigured, the scheduled sync skips without writing anything, and the heartbeat tiles keep working on their own.
`,
  "sensitive-scan": `# Sensitive Scan

Two related defenses against sensitive data leaving — or coming back out of — your AI tools: an active prober that tests reachable endpoints, and passive inspection of live proxy traffic.

## Probe targets

Probing runs against AI gateways you have configured — **OpenRouter**, **Helicone**, **Portkey**, and **LiteLLM**. Each configured gateway becomes a target; unconfigured ones are skipped. Configure credentials at **Integrations** or **Settings → Provider Admin APIs**.

## What the probes test

Four probes, each a crafted prompt that a well-configured endpoint should refuse:

- **System prompt extraction** (\`prompt_disclosure\`) — attempts to make the model reveal its own system prompt. Critical if it leaks.
- **Credential / secret recall** (\`secret_disclosure\`) — attempts to surface API keys or credentials from context or training data. Critical if it leaks.
- **PII recall** (\`pii_disclosure\`) — attempts to elicit personal data about individuals. Critical if it leaks.
- **Training-data exfiltration** (\`data_exfiltration\`) — attempts verbatim recall of training material. Raises a warning rather than a critical.

A probe that leaks creates a finding with its category and severity, and raises an alert. Each target is recorded with a status — \`probed\`, \`skipped\` (not configured), or \`error\` — and a finding count, so a clean result reads as "probed, 0 findings" rather than as silence. Distinguishing \`probed\` from \`skipped\` matters: a skipped target was never tested.

## Inline response DLP

Independently of probing, traffic through the proxy is inspected in both directions against four built-in detectors:

- **Secret or credential extraction attempt** — the prompt is fishing for credentials.
- **Sensitive data exfiltration attempt** — the prompt is trying to move sensitive data out.
- **Sensitive data pasted into prompt** — a user pasted sensitive material **in**. Often the most common finding, and usually careless rather than malicious.
- **API key or token present** — a live-looking key or token appears in the text.

Matches are recorded as findings and linked to an alert. Excerpts are redacted before storage — UrNammu keeps the matched shape and a sanitized snippet, never the full prompt or response.

## Scheduling

Probes can run on a schedule as well as on demand, so a gateway that silently changes its retention or system-prompt handling is caught without someone remembering to check. Findings accumulate on this page and in **Alerts**.

## Reading a finding

Treat a finding as a lead, not a verdict. A gateway may legitimately echo a system prompt you authored yourself, and a detector may match a documentation example that merely looks like a key. Confirm before escalating, and mark genuine non-issues so the noise does not train your team to skim past the real ones.
`,
  settings: `# Settings

Most settings require \`ADMIN\`. Secret values are encrypted in the database with \`SETTINGS_ENCRYPTION_KEY\`.

## Sections

- **Overview** — jump-off page to every settings area.
- **General** — choose the AI provider (Anthropic / OpenAI) and model used for in-app AI features (risk suggestion, compliance gap analysis, agent risk review, summarization). The global **policy enforcement mode** for the proxy — Off / Dry run / Enforce — is also set here, along with Azure Monitor access for Proxy Health and the **Data Retention** card.
- **Provider Admin APIs** — admin keys for org telemetry: Anthropic, OpenAI, Cursor, Google Gemini billing export, plus the AI gateways. The **Background Provider Sync** card sets the global auto-sync default and interval, and a per-provider table lets each provider (including Claude Code analytics and each gateway) override both, with its last run, outcome, and next-due time. Unset overrides inherit the global value. Anomaly thresholds, governance-automation notice days, and **Usage Attribution** live here too: a default registered AI system per provider (Anthropic, OpenAI, LiteLLM, Cursor) and per-API-key overrides that map an individual provider key to a system. Mappings apply to both usage and cost rows on the next sync and drive the Cost by Governed System / Cost by API Key panels on Oversight.
- **Proxy Setup** — shared \`PROXY_SECRET\` for the transparent Claude / OpenAI proxy. Generates ready-to-paste config for Claude Code (managed settings or per-user). Supports attribution headers: \`x-user-email\`, \`x-department\`, \`x-ai-system-id\`, \`x-agent-id\`. For per-user attribution in Claude Code, developers add \`export PROXY_USER_EMAIL="$(git config user.email)"\` to their shell profile.
- **Users & Identity** — manage users and roles. Configure Google OAuth, Microsoft 365 / Entra ID sign-in, and password-backed local accounts. The **Directory sync** card (see below) pulls the people directory from Google Workspace and/or Microsoft Entra ID.
- **Shadow AI** — credentials and scan controls for every discovery source (Google Workspace, Microsoft 365, Hexnode, CrowdStrike, Netskope), plus DNS / proxy import, the blocklist feed token, and the enforcement readiness summary.
- **Reporting** — email delivery for scheduled reports, via Resend. Schedules save without it but never send.

For a catalog view of every external service and whether it is connected, use the **Integrations** page instead. Settings is where behavior is configured; Integrations is where you see coverage at a glance.

## Directory sync

**Settings → Users & Identity → Directory sync** keeps a copy of your identity provider's people directory (\`DirectoryPerson\`) so the rest of the platform can stop guessing who someone is. One card per source, each with an **Auto-sync** toggle, an **Interval** (default 24 h), the last run's outcome and counts, active / deactivated people counts, and a **Sync now** button. **Both sources are off by default.**

- **Google Workspace directory** — reuses the Shadow AI service account and admin email. The service account's domain-wide delegation grant must also include \`https://www.googleapis.com/auth/admin.directory.user.readonly\`; without it the run fails with an authorization error and nothing is written.
- **Microsoft Entra ID directory** — reuses the Shadow AI tenant app. The app registration needs the Graph application permission \`User.Read.All\` (admin consented). Guest accounts (\`#EXT#\` in the UPN) are skipped unless **Guest accounts** is set to include them.

Each run is a full sync: every person returned is upserted (email addresses lower-cased, aliases deduped and never repeating the primary), and anyone in that source who was **not** returned is marked deactivated. That deactivation step only runs after at least one page was fetched successfully and the listing was not cut short by the 100-page cap, so a credentials failure or an oversized tenant can never mass-deactivate the directory. Runs are recorded as \`ProviderSyncRun\` rows with sync type \`directory\`.

What the directory feeds:

- **Usage by Person** — observed emails are resolved through the alias map, so one person seen under two addresses becomes one row; name and department come from the directory first. Rows for deactivated accounts carry a **Deactivated** badge.
- **Shadow AI** — each discovered tool's user list is rolled up by department (for example "Engineering 4 · Sales 2").
- **Offboarding** — when a directory account goes inactive and a UrNammu user with the same email is \`ACTIVE\`, that user is set to \`SUSPENDED\` (never deleted), their sessions are cleared, and an audit log entry records why.
- **Usage after deactivation** — the hourly governance-automation cron raises a \`HIGH\` alert (source \`usage_after_deactivation\`) when a deactivated person's email or alias still shows activity in the proxy buckets, coding-assistant daily stats, or the proxy request log dated after the deactivation. One alert per person per 7 days.

Environment fallbacks: \`DIRECTORY_SYNC_GOOGLE_WORKSPACE_ENABLED\`, \`DIRECTORY_SYNC_GOOGLE_WORKSPACE_INTERVAL_HOURS\`, \`DIRECTORY_SYNC_MICROSOFT_365_ENABLED\`, \`DIRECTORY_SYNC_MICROSOFT_365_INTERVAL_HOURS\`, \`DIRECTORY_SYNC_INCLUDE_GUESTS\`. The daily crons run at 04:10 UTC (Google) and 04:20 UTC (Microsoft) and only do work when the source is enabled, configured, idle, and past its interval.

## Enforcement readiness

**Settings → Shadow AI** summarizes whether a \`BLOCKED\` shadow-AI decision can actually be enforced, across three checks:

- **Identity — Google Workspace**
- **Identity — Microsoft 365 (Entra)**
- **Network — Blocklist feed**

Identity enforcement disables a federated app at the IdP; the network feed publishes blocked domains for a DNS, proxy, firewall, or CASB to consume. Both are optional, but with neither configured a block is only a recorded decision. Microsoft app-disable additionally needs admin consent for the relevant Graph permission — the readiness card reports it as \`failed\` rather than silently doing nothing.

The blocklist feed token can be generated here (64 random characters). The feed fails closed: with no token set it returns \`503\` instead of serving unauthenticated.

## Data retention

**Settings → General → Data Retention** sets how many days of raw collection rows the nightly prune crons keep. Each table has its own window; blank means "use the environment variable or built-in default", and \`0\` disables pruning for that table.

- **Proxy request log** (\`APIUsageLog\`) — default 180 days. The hourly and daily usage / cost buckets keep the totals, so dashboards do not change when raw rows are pruned.
- **Agent tool calls** (\`AgentToolCall\`) — default 180 days. Agent tool profiles keep the counts.
- **Policy denials** (\`PolicyDenial\`) — default 365 days.
- **Provider raw snapshots** (\`ProviderRawSnapshot\`) — default 14 days. Raw admin-API payloads captured during provider syncs, kept only for debugging.
- **Proxy health snapshots** (\`ProxyHealthSnapshot\`) — default 90 days.
- **Scan runs** (\`SensitiveScan\`, \`ProviderSecurityScan\`) — default 365 days. The newest run overall and the newest run covering each provider are always kept, so the latest posture per provider never disappears.
- **Claude Code telemetry** and **Cursor telemetry** — default 30 days each; these are the existing OTel prune crons.

Usage and cost buckets are the long-term aggregate and are **never** pruned. The prune runs daily at 03:45 UTC (\`/api/cron/prune-collection\`), deletes oldest-first in batches of 5,000, and reports per-table \`deleted\` / \`remaining\` counts. A backlog too large for one run drains over consecutive nights.

## Roles

- \`ADMIN\` — everything.
- \`COMPLIANCE_OFFICER\` — create / assign policies, approve stages, create exceptions, upload evidence, close incidents.
- \`VIEWER\` — read-only.

## Tips

- The first user to sign in via Google OAuth is auto-promoted to \`ADMIN\`. Subsequent users default to \`VIEWER\`.
- Settings UI values **win over** environment variables. Env vars are the fallback when the DB value is absent.
- Do **not** rotate \`SETTINGS_ENCRYPTION_KEY\` in place — encrypted settings will become unreadable.
`,
};

/**
 * Map a Next.js pathname to a help key. Falls back to "dashboard".
 * Order matters — most specific routes come first.
 */
export function helpKeyForPath(pathname: string): HelpKey {
  if (pathname.startsWith("/registry/") && pathname !== "/registry/new") return "registry-detail";
  if (pathname.startsWith("/dashboard")) return "dashboard";
  if (pathname.startsWith("/registry")) return "registry";
  if (pathname.startsWith("/agents")) return "agents";
  if (pathname.startsWith("/risk-center")) return "risk-center";
  if (pathname.startsWith("/compliance")) return "compliance";
  if (pathname.startsWith("/shadow-ai")) return "shadow-ai";
  if (pathname.startsWith("/oversight")) return "oversight";
  if (pathname.startsWith("/alerts")) return "alerts";
  if (pathname.startsWith("/executive")) return "executive";
  if (pathname.startsWith("/reports")) return "reports";
  if (pathname.startsWith("/integrations")) return "integrations";
  if (pathname.startsWith("/proxy-health")) return "proxy-health";
  if (pathname.startsWith("/sensitive-scan")) return "sensitive-scan";
  if (pathname.startsWith("/settings")) return "settings";
  return "dashboard";
}
